### ISSUE TITLE
issue with tornado 6.0

### ISSUE THREAD

**Issue by 0x55AAh** [miguelgrinberg/python-engineio#104]
In get_tornado_handler we have
```
async def get(self, *args, **kwargs):
    if self.request.headers.get('Upgrade', '').lower() == 'websocket':
        super().get(*args, **kwargs)
    await engineio_server.handle_request(self)
```
But need for
```
async def get(self, *args, **kwargs):
    if self.request.headers.get('Upgrade', '').lower() == 'websocket':
        await super().get(*args, **kwargs)
    await engineio_server.handle_request(self)
```
In tornado 6.0+ tornado.websocket.WebSocketHandler has an async method get

**Comment by miguelgrinberg** [comment]
Yes, I was aware of this change while they were in beta. Not sure why they chose to do such a breaking change, makes it hard to support both the 5.x and 6.x releases at the same time.

**Comment by 0x55AAh** [comment]
Hmmm, even with this fix something has broken... Aren't you going add supporting 6.0+?

**Comment by miguelgrinberg** [comment]
No, sorry, I didn't fix it yet. I saw it on their beta releases, and hoped they would eventually implement some sort of dual compatibility, which they didn't. So now I'll probably have to break 5.x to support 6.x.

**Comment by miguelgrinberg** [comment]
@0x55AAh can i ask you to install the master branch of this repo and retest? I believe I have addressed the incompatibility with Tornado 6, while remaining compatible with v5. Thanks.

**Comment by 0x55AAh** [comment]
Ok. I wil test.

**Comment by DeoLeung** [comment]
```bash
socketio_1        | 2019-06-01 21:35:13,880.880 app:1   INFO    101 GET /socket.io/?token=3edcc438-0baf-4d1b-b0cb-3cfd5fe82d9a&EIO=3&transport=websocket (172.16.148.77) 1.04ms
socketio_1        | 2019-06-01 21:35:13,880.880 asyncio_pubsub_manager:1        INFO    aioredis backend initialized.
socketio_1        | 2019-06-01 21:35:13,881.881 asyncio_server:1        WARNING Application rejected connection
socketio_1        | 2019-06-01 21:35:13,882.882 app:1   ERROR   Task exception was never retrieved
socketio_1        | future: <Task finished coro=<AsyncServer.handle_request() done, defined at /usr/local/lib/python3.7/site-packages/engineio/asyncio_server.py:169> exception=RuntimeError('Method not supported for Web Sockets')>
socketio_1        | Traceback (most recent call last):
socketio_1        |   File "/usr/local/lib/python3.7/site-packages/engineio/asyncio_server.py", line 275, in handle_request
socketio_1        |     r['response'], environ)
socketio_1        |   File "/usr/local/lib/python3.7/site-packages/engineio/async_drivers/tornado.py", line 138, in make_response
socketio_1        |     tornado_handler.set_status(int(status.split()[0]))
socketio_1        |   File "/usr/local/lib/python3.7/site-packages/tornado/websocket.py", line 627, in _raise_not_supported_for_websockets
socketio_1        |     raise RuntimeError("Method not supported for Web Sockets")
socketio_1        | RuntimeError: Method not supported for Web Sockets
```

websocket does not support using `set_status`

using `3.7.0`

**Comment by DeoLeung** [comment]
oh, it happens only when connection is rejected, same in `3.5.1`

**Comment by miguelgrinberg** [comment]
@DeoLeung What version of Tornado are you using, and can I see the code as well?

**Comment by DeoLeung** [comment]
```python
import asyncio
import logging

import socketio
import uvloop
from socketio import AsyncNamespace
from tornado import httpserver
from tornado import web

asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())


class Default(AsyncNamespace):

  async def on_connect(self, sid: str, env: dict):
    logging.debug('login')
    # here we reject the connection
    return False

  def on_disconnect(self, sid):
    logging.debug('logout')

  async def trigger_event(self, event, *args):
    """log all events"""
    logging.debug('%s %s', event, args)
    return await super().trigger_event(event, *args)


def make_app() -> web.Application:
  _loop = asyncio.get_event_loop()
  sio = socketio.AsyncServer(async_mode='tornado')
  sio.register_namespace(Default(namespace='/'))
  router = [('/socket.io/', socketio.get_tornado_handler(sio))]
  app = web.Application(router, debug=True)
  return app


if __name__ == "__main__":
  logging.basicConfig(level=logging.DEBUG)
  tornado_app = make_app()
  loop = asyncio.get_event_loop()
  http_server = httpserver.HTTPServer(tornado_app)
  http_server.listen(8890)

  try:
    loop.run_forever()
  finally:
    loop.close()
```
```python
# client
import logging
import time

from socketio import Client

logging.basicConfig(level=logging.DEBUG)

sio = Client()
sio.connect('http://localhost:8890', transports='websocket')
```

happens oh tornado `5.1.1` and `6.0.2`
