### ISSUE TITLE
Python 3.7, using gevent_uwsgi causes "Invalid async_mode specified"

### ISSUE THREAD

**Issue by brunoais** [miguelgrinberg/python-engineio#106]
I'm using python 3.7 and when I try to start SocketUI with `async_mode='gevent_uwsgi'` an exception is raised:
```
Connected to pydev debugger (build 191.6605.12)
Traceback (most recent call last):
  File "/snap/pycharm-community/123/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/snap/pycharm-community/123/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-community/123/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/123/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "socketio_exec.py", line 10, in <module>
    socketio = SocketIO(app, engineio_logger=True, async_mode='gevent_uwsgi')
  File "/var/pycharm_venvs/fullstack-coding-challenge_mine/lib/python3.7/site-packages/flask_socketio/__init__.py", line 163, in __init__
    self.init_app(app, **kwargs)
  File "/var/pycharm_venvs/fullstack-coding-challenge_mine/lib/python3.7/site-packages/flask_socketio/__init__.py", line 221, in init_app
    self.server = socketio.Server(**self.server_options)
  File "/var/pycharm_venvs/fullstack-coding-challenge_mine/lib/python3.7/site-packages/socketio/server.py", line 89, in __init__
    self.eio = self._engineio_server_class()(**engineio_options)
  File "/var/pycharm_venvs/fullstack-coding-challenge_mine/lib/python3.7/site-packages/engineio/server.py", line 129, in __init__
    raise ValueError('Invalid async_mode specified')
ValueError: Invalid async_mode specified
```

A short investigation with the debugger appears to show that:
`importlib.import_module(
                    'engineio.async_drivers.gevent_uwsgi')`
Generates the response:
`{ModuleNotFoundError}No module named 'uwsgi'.`
This was tested with a debugger stopped at: https://github.com/miguelgrinberg/python-engineio/blob/88400ba57cb5173e36d8305fbdb10b483895be08/engineio/server.py#L118

**Using python version:**  3.7.2
**Using SocketIO version:** 3.3.2
**EngineIO version:** 3.4.4

**Comment by miguelgrinberg** [comment]
Did you install uwsgi?

**Comment by brunoais** [comment]
I did.
