### ISSUE TITLE
Getting AttributeError: module 'engineio' has no attribute 'WSGIApp' on Linux

### ISSUE THREAD

**Issue by YuriAFGomes** [miguelgrinberg/python-engineio#126]
I'm using Linux Mint 19.1 Cinnamon, and as I try to run a flask application via `flask run` , I get the following error:

 ```Traceback (most recent call last):
  File "/usr/bin/flask", line 11, in <module>
    load_entry_point('Flask==0.12.2', 'console_scripts', 'flask')()
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 423, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 152, in __init__
    self._load_unlocked()
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 176, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 90, in locate_app
    __import__(module)
  File "/home/yuri/Downloads/project2/application.py", line 4, in <module>
    from flask_socketio import SocketIO, emit
  File "/usr/lib/python3/dist-packages/flask_socketio/__init__.py", line 7, in <module>
    from socketio import socketio_manage
  File "/home/yuri/.local/lib/python3.6/site-packages/socketio/__init__.py", line 11, in <module>
    from .middleware import WSGIApp, Middleware
  File "/home/yuri/.local/lib/python3.6/site-packages/socketio/middleware.py", line 4, in <module>
    class WSGIApp(engineio.WSGIApp):
AttributeError: module 'engineio' has no attribute 'WSGIApp'
```
This application requires the installation of two packages: flask and flask_socketio.
This is my `pip3 freeze` output:

```apt-clone==0.2.1
apturl==0.5.2
beautifulsoup4==4.6.0
Brlapi==0.6.6
certifi==2018.1.18
chardet==3.0.4
Click==7.0
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
cupshelpers==1.0
defer==1.0.6
Flask==1.1.1
Flask-SocketIO==4.1.0
httplib2==0.9.2
idna==2.6
itsdangerous==1.1.0
Jinja2==2.10.1
louis==3.5.0
macaroonbakery==1.1.3
Mako==1.0.7
MarkupSafe==1.1.1
nemo-emblems==4.0.2
netifaces==0.10.4
onboard==1.4.1
PAM==0.4.2
pexpect==4.2.1
Pillow==5.1.0
protobuf==3.0.0
psutil==5.4.2
pycairo==1.16.2
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0.1
pygobject==3.26.1
PyICU==1.9.8
pyinotify==0.9.6
pymacaroons==0.13.0
PyNaCl==1.1.2
pyRFC3339==1.0
python-apt==1.6.4
python-debian==0.1.32
python-engineio==3.8.2.post1
python-socketio==4.2.0
python-xapp==1.4.0
python-xlib==0.20
pytz==2018.3
pyxdg==0.25
PyYAML==3.12
reportlab==3.4.0
requests==2.18.4
requests-unixsocket==0.1.5
sessioninstaller==0.0.0
setproctitle==1.1.10
six==1.12.0
system-service==0.3
systemd-python==234
ubuntu-drivers-common==0.0.0
ufw==0.36
urllib3==1.22
vboxapi==1.0
Werkzeug==0.15.4
xkit==0.0.0
```

I have successfully ran this same flask application on Windows 7 today. Is there something I can do to avoid this attribute error? I'm using python 3.6.8 on both Linux and Windows.

**Comment by miguelgrinberg** [comment]
Do you have a module or package named `engineio` in your application? If yes, rename it and try again.

**Comment by YuriAFGomes** [comment]
No, I haven't created any modules called engineio. This is my application as of now ```import os

from flask import Flask, render_template, url_for
from flask_socketio import SocketIO, emit

app = Flask(__name__)
app.config["SECRET_KEY"] = os.getenv("SECRET_KEY")
socketio = SocketIO(app)


@app.route("/")
def index():
    return render_template("index.html")```

**Comment by miguelgrinberg** [comment]
open a Python shell with the same virtual environment, then type the following:

```
>>> import engineio
>>> dir(engineio)
```
and show me the output.

**Comment by YuriAFGomes** [comment]
```
>>> import engineio
>>> dir(engineio)
['AsyncServer', 'Middleware', 'Server', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'asyncio_server', 'asyncio_socket', 'exceptions', 'middleware', 'packet', 'payload', 'server', 'socket', 'sys']
```

**Comment by miguelgrinberg** [comment]
@YuriAFGomes I don't have an explanation, but the output that you are getting suggests that you are using an old version of python-engineio. Your dependency listing indicates you have the last version, however.

I suggest you uninstall python-engineio and then reinstall it. Also add `--no-cache-dir` option to your pip command to make sure it goes to pypi to grab a fresh copy.

**Comment by YuriAFGomes** [comment]
That solved the problem for me. Thank you so much!
