### ISSUE TITLE
task_done() called too many times

### ISSUE THREAD

**Issue by eiso** [miguelgrinberg/python-engineio#135]
I have tried to research this online but couldn't find anything. I have included the error message and the code. The server is setup with `aiohttp`.

I am happy to provide any more insights. I appreciate someone taking a look. Thank you.

I manage to get results but every couple of runs it provides this error:

```shell
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/eiso/.local/lib/python3.7/site-packages/engineio/client.py", line 627, in _write_loop
    self.queue.task_done()
  File "/usr/lib/python3.7/queue.py", line 74, in task_done
    raise ValueError('task_done() called too many times')
ValueError: task_done() called too many times
```

```Python
import socketio
import sys
from time import sleep

sio = socketio.Client()
host = 'http://localhost:5000'

class Observable(object):

    def __init__(self):
        try:     
            sio.connect(host)
        except:
            pass

    def _setCell(self, cell):
        self._cell = cell

    def _getCell(self):
        return self._cell

    def _setCellRange(self, cellrange):
        self._cellrange = cellrange

    def _getCellRange(self):
        return self._cellrange

    cell = property(_getCell, _setCell)
    cellrange = property(_getCellRange, _setCellRange)

    def subscribe(self, callback):
        self.callback = callback

    @sio.event
    def sendcell(self):
        sio.emit('receivecell', {'cell': self.cell}, callback=self.callback)

    @sio.event
    def sendrange(self):
        sio.emit('receiverange', {'range': self.cellrange}, callback=self.callback)

class HandleCallBack:
    response = None

    def doCallback(self, data):
        #print(data)
        self.response = data
        sio.disconnect()

class Cell(object):

    def __init__(self, address):
        self.address = address

        self._h = HandleCallBack()
        self._o = Observable()
        self._o.subscribe(self._h.doCallback)

    def value(self):
        self._o.cell = self.address
        self._o.sendcell()
        
        while self._h.response is None:
            try:
                sleep(0.005)
            except:
                pass
  
        return self._h.response

class Range(object):

    def __init__(self, address):
        self.address = address

        self._h = HandleCallBack()
        self._o = Observable()
        self._o.subscribe(self._h.doCallback)

    def value(self):
        self._o.cellrange = self.address
        self._o.sendrange()
        while self._h.response is None:
            try:
                sleep(0.005)
            except:
                pass

        return self._h.response


if __name__ == '__main__':
    import timeit
    print(timeit.timeit('Range("Sheet1!A1:Sheet1!A100").value()', setup="from __main__ import Range", number=10))
```

**Comment by miguelgrinberg** [comment]
Any chance you have multiple `Observable` objects in your application? That could be a problem, because you are always using the same Socket.IO client instance.

**Comment by luizcz** [comment]
This also happened to me but I am not able to debug to see where exactly it happened. In my case I have a thread that keeps trying to make the first connection because sometimes the server is not available in the first try of connection. Also, we use polling as a fall back due to some restrictions.

**Comment by miguelgrinberg** [comment]
@luizcz my guess is that your retry logic interferes with the library's own and sometimes you end up having two active connections on the same client instance.

**Comment by luizcz** [comment]
I had to make the thread because when the application with the client starts and the server is no up yet. Then I get socketio.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=5555): Max retries exceeded with url. I think there is a cleaner solution but I did not arrive to that. Your guess makes sense. I will rethink my solution.

**Comment by HouJP** [comment]
Hey guys, I ran into the same issue many times :p

## Logs

```
ERROR (2025-02-18 21:43:13) The connection to the server failed
ERROR (2025-02-18 21:44:12) The connection to the server failed
ERROR (2025-02-18 21:44:27) The connection to the server failed
ERROR (2025-02-18 21:44:52) The connection to the server failed
ERROR (2025-02-18 21:45:01) The connection to the server failed
ERROR (2025-02-18 21:45:26) The connection to the server failed
ERROR (2025-02-18 21:45:36) The connection to the server failed
INFO (2025-02-18 21:45:49) Connected to the server, sid=cQJshtlH8bZhYbM6BLOK
INFO (2025-02-18 21:46:22) Disconnected from the server
ERROR (2025-02-18 21:46:29) The connection to the server failed
ERROR (2025-02-18 21:46:35) The connection to the server failed
ERROR (2025-02-18 21:46:44) The connection to the server failed
ERROR (2025-02-18 21:47:55) The connection to the server failed
ERROR (2025-02-18 21:48:23) The connection to the server failed
ERROR (2025-02-18 21:48:35) The connection to the server failed
ERROR (2025-02-18 21:49:11) The connection to the server failed
ERROR (2025-02-18 21:49:23) The connection to the server failed
ERROR (2025-02-18 21:49:33) The connection to the server failed
ERROR (2025-02-18 21:49:46) The connection to the server failed
ERROR (2025-02-18 21:49:57) The connection to the server failed
ERROR (2025-02-18 21:50:07) The connection to the server failed
ERROR (2025-02-18 21:50:17) The connection to the server failed
ERROR (2025-02-18 21:50:45) The connection to the server failed
ERROR (2025-02-18 21:50:54) The connection to the server failed
ERROR (2025-02-18 21:51:24) The connection to the server failed
ERROR (2025-02-18 21:51:34) The connection to the server failed
ERROR (2025-02-18 21:51:47) The connection to the server failed
ERROR (2025-02-18 21:51:58) The connection to the server failed
ERROR (2025-02-18 21:52:09) The connection to the server failed
ERROR (2025-02-18 21:52:20) The connection to the server failed
ERROR (2025-02-18 21:52:32) The connection to the server failed
ERROR (2025-02-18 21:52:42) The connection to the server failed
ERROR (2025-02-18 21:53:07) The connection to the server failed
ERROR (2025-02-18 21:53:19) The connection to the server failed
ERROR (2025-02-18 21:53:30) The connection to the server failed
ERROR (2025-02-18 21:53:42) The connection to the server failed
ERROR (2025-02-18 21:53:52) The connection to the server failed
Exception in thread Thread-211074:
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/hugues/Library/Python/3.9/lib/python/site-packages/engineio/client.py", line 580, in _write_loop
    self.queue.task_done()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/queue.py", line 75, in task_done
    raise ValueError('task_done() called too many times')
ValueError: task_done() called too many times
```

## Background

The program has only one socketio client and I didn't have any retry logic.

Could you help to take a look? Thanks in advance :p

**Comment by HouJP** [comment]
Sure, thanks for the reply! The source code of `Socket` class as shown below.

```python
class Socket(object):

    def __init__(self, params: Params, mongo: MongoDB):
        self._params = params
        self._mongo = mongo
        
        http_session = requests.Session()
        http_session.verify = True
        self._client = socketio.Client(
            http_session=http_session,
        )

        @self._client.event
        def connect():
            log_util.info(f"Connected to the server, sid={self._client.sid}")

        @self._client.event
        def connect_error(data):
            log_util.error("The connection to the server failed")

        @self._client.event
        def disconnect():
            log_util.info("Disconnected from the server")
        
        @self._client.event
        def update_user(params):
            self._mongo.update_user(params)
        
        @self._client.event
        def add_message(params):
            self._mongo.add_message(params)
            
        @self._client.event
        def add_counter(params):
            self._mongo.add_counter(params)
            
        @self._client.event
        def add_topic(params):
            self._mongo.add_topic(params)
            
        self._client.connect(
            http_util.get_socketio_addr(self._params.local),
            headers={
                UserConstants.KEY_MOBILE: self._params.mobile,
                UserConstants.KEY_TOKEN: get_univ_token(mobile=self._params.mobile),
            },
        )
    

    @property
    def client(self) -> socketio.Client:
        return self._client
```

As you can see, this class is pretty simple, and I have no idea where the exception comes from.

**Comment by miguelgrinberg** [comment]
Thanks. Can you also generate a new log dump but this time with verbose logging enabled on the client? Add `logger=True, engineio_logger=True` arguments to the client constructor.

**Comment by HouJP** [comment]
Thanks Miguel!

Currently we're not able to reproduce this exception. The only change to the server is that we removed the setting field of `wait_timeout=10` (this is a private repo so I attached a snapshot). Hope it helps!

Apologies that I'm not allowed to enable the logger and reproduce the exception on the production server :p

Please feel free to let me know if I can provide any other information.

![Image](https://github.com/user-attachments/assets/7118c720-c0df-4769-a61d-a6cab4775591)

**Comment by miguelgrinberg** [comment]
@HouJP It isn't clear if the issue occurs when the wait timeout is 10 seconds, or when it is left to the default of 1 second. Can you please clarify which case reproduces the error?

**Comment by HouJP** [comment]
@miguelgrinberg Sure :p I attached a detailed snapshot to prove this exception is related to the setting of `wait_timeout` AFAIK.

Please feel free to let me know if you need any other information.

![Image](https://github.com/user-attachments/assets/ac3cbb79-af92-43e0-a9f1-7fff477f1ed1)

**Comment by HouJP** [comment]
Please let me know if I should create a separate issue considering the root cause might be different from things in 6 years ago (2019), lol
