### ISSUE TITLE
Tornado Dependency

### ISSUE THREAD

**Issue by smalls12** [miguelgrinberg/python-engineio#141]
Hello,

I'm working on updating buildroot to install python-flask-socketio.
Working my way through the dependencies I installed python-socketio, then python-engineio.
When attempting to start a flask-socketio server I got the following error:

```
# python3 bg_event.py 
Traceback (most recent call last):
  File "usr/lib/python3.7/site-packages/socketio/tornado.py", line 4, in <module>
  File "usr/lib/python3.7/site-packages/engineio/async_drivers/tornado.py", line 6, in <module>
ModuleNotFoundError: No module named 'tornado'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bg_event.py", line 6, in <module>
    from flask_socketio import SocketIO, join_room, leave_room, send, emit
  File "usr/lib/python3.7/site-packages/flask_socketio/__init__.py", line 21, in <module>
  File "usr/lib/python3.7/site-packages/socketio/__init__.py", line 12, in <module>
  File "usr/lib/python3.7/site-packages/socketio/tornado.py", line 7, in <module>
ModuleNotFoundError: No module named 'engineio.async_tornado'
```
The fix was to simply install tornado `pip install tornado`.

Should this dependency be reflected in the setup.py ?

A separate issue is to link this dependency in the buildroot Config.in for python-engineio.

**Comment by miguelgrinberg** [comment]
Tornado is an optional dependency, it is not required.

What version of python-socketio do you have installed? I believe it must be a fairly old version that is incompatible with recent versions of python-engineio.

**Comment by smalls12** [comment]
It looks like buildroot installs python-socketio v4.0.2.

I will check for the latest.

**Comment by miguelgrinberg** [comment]
Please reopen if you still need assistance with this issue.

**Comment by mucahiddogan** [comment]
ı have that error too
