### ISSUE TITLE
Improving Websocket-client error handling

### ISSUE THREAD

**Issue by harmon** [miguelgrinberg/python-engineio#154]
> TL;DR: I have a suggested fix at the bottom to handle any websocket errors which are currently not caught.

I've been seeing an unhandled Websocket-client library error pop up pretty often, especially when the socketio server we are connecting to gets disconnected from our client.

```
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/socketio/client.py", line 556, in _handle_reconnect
    socketio_path=self.socketio_path)
  File "/usr/local/lib/python3.7/site-packages/socketio/client.py", line 268, in connect
    engineio_path=socketio_path)
  File "/usr/local/lib/python3.7/site-packages/engineio/client.py", line 184, in connect
    url, headers, engineio_path)
  File "/usr/local/lib/python3.7/site-packages/engineio/client.py", line 366, in _connect_websocket
    cookie=cookies)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 514, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 226, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/local/lib/python3.7/site-packages/websocket/_handshake.py", line 79, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/local/lib/python3.7/site-packages/websocket/_handshake.py", line 158, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/usr/local/lib/python3.7/site-packages/websocket/_http.py", line 305, in read_headers
    line = recv_line(sock)
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 123, in recv_line
    c = recv(sock, 1)
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 115, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
```
I think if you added the top-level "WebsocketException" to the following try/except, it would appropriately retry and throw the internal engineio.ConnectionError exception, which is caught by socketio nicely:

https://github.com/miguelgrinberg/python-engineio/blob/02a2c705b01f171edea106a7ee867b6112074853/engineio/client.py#L362-L377

Here's the top-level exception from the `websocket-client` library that their other websocket exceptions derive from:

https://github.com/websocket-client/websocket-client/blob/3c25814664fef5b78716ed8841123ed1c0d17824/websocket/_exceptions.py#L29-L33

Proposed change:

```
        try:
            if not self.ssl_verify:
                ws = websocket.create_connection(
                    websocket_url + self._get_url_timestamp(), header=headers,
                    cookie=cookies, sslopt={"cert_reqs": ssl.CERT_NONE})
            else:
                ws = websocket.create_connection(
                    websocket_url + self._get_url_timestamp(), header=headers,
                    cookie=cookies)
-       except (ConnectionError, IOError):
+       except (ConnectionError, IOError, websocket.WebSocketException):
            if upgrade:
                self.logger.warning(
                    'WebSocket upgrade failed: connection error')
                return False
            else:
                raise exceptions.ConnectionError('Connection error')
```

**Comment by harmon** [comment]
https://github.com/miguelgrinberg/python-engineio/issues/154
