### ISSUE TITLE
socket.handle_get_request() returns list containing NoneTypes

### ISSUE THREAD

**Issue by jonathanvanschenck** [miguelgrinberg/python-engineio#164]
I'm working on a flask app that uses gunicorn, evenlet and nginx on an AWS EC2 server. Occasionally, engineio throws me an error that the 'NoneType' object has no attribute 'encode'. Here's the error log:
```bash
Traceback (most recent call last):
  File "/home/ubuntu/A-Whole-Apple/venv/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/home/ubuntu/A-Whole-Apple/venv/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 106, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/ubuntu/A-Whole-Apple/venv/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/A-Whole-Apple/venv/lib/python3.6/site-packages/flask_socketio/__init__.py", line 46, in __call__
    start_response)
  File "/home/ubuntu/A-Whole-Apple/venv/lib/python3.6/site-packages/engineio/middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/ubuntu/A-Whole-Apple/venv/lib/python3.6/site-packages/socketio/server.py", line 534, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/ubuntu/A-Whole-Apple/venv/lib/python3.6/site-packages/engineio/server.py", line 379, in handle_request
    jsonp_index=jsonp_index)
  File "/home/ubuntu/A-Whole-Apple/venv/lib/python3.6/site-packages/engineio/server.py", line 583, in _ok
    b64=b64, jsonp_index=jsonp_index)}
  File "/home/ubuntu/A-Whole-Apple/venv/lib/python3.6/site-packages/engineio/payload.py", line 21, in encode
    encoded_packet = pkt.encode(b64=b64)
AttributeError: 'NoneType' object has no attribute 'encode'
```
If I have `engineio.server.handle_request` print the "packet" object before it gets passed to `engineio.server.__ok`, the print out is:
```python3
[<engineio.packet.Packet object at 0x7fa23d0bf2b0>, None]
```
so that in this particular case, there is a mixture of `None` and `Packet` objects in the list (which I'm pretty sure is a bug?)

I've traced the generation of the packet list back: `server.__ok` from `server.handle_request` from `socket.handle_get_request` from `socket.poll` from `packets.append(self.queue.get(block=False))`. Somehow, self.queue is returning a `Packet` object, then a `NoneType` before raising the empty exception? This is pretty far above my pay grade and I'm not totally sure what is going wrong.

I'm able to hack together a solution by inserting:
```python3
pkt_clean = packets
if type(packets) == list:
    pkt_clean = [p for p in packets if not p is None]
 return {'status': '200 OK',
             headers': headers,
             'response': payload.Payload(packets=pkt_clean).encode(
              b64=b64, jsonp_index=jsonp_index)}
```
Near line 580 in `engineio/server.py` in `server._ok`

**Comment by miguelgrinberg** [comment]
Thanks, I'll look into it.

**Comment by jonathanvanschenck** [comment]
Thanks for the quick response!

**Comment by miguelgrinberg** [comment]
@jonathanvanschenck can I ask you to retest with the master branch? Thanks!
