### ISSUE TITLE
flask_socketio KeyError when calling SocketIO.disconnect

### ISSUE THREAD

**Issue by arbel03** [miguelgrinberg/python-engineio#172]
Edit: https://github.com/miguelgrinberg/python-engineio/pull/168 Should fix

When disconnecting a user using `flask_socketio.SocketIO.disconnect()`, 
I am getting a KeyError as follows (see log).

It seems like flask_socketio is closing the open HTTP client socket when calling disconnect().
Then eventlet continues to handle the request and in `server.py` the following code causes the bug:
```python
# server.py 518:0
 if transport == 'websocket':
            ret = s.handle_get_request(environ, start_response)
            if s.closed:
                # websocket connection ended, so we are done
                del self.sockets[sid]
            return ret
        else:
            s.connected = True
            headers = None
            if self.cookie:
```

Traceback:
```
Disconnecting user
Traceback (most recent call last):
  File "C:\Git\neighbors_server\lib\site-packages\eventlet\wsgi.py", line 566, in handle_one_response
    result = self.application(self.environ, start_response)
  File "C:\Git\neighbors_server\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Git\neighbors_server\lib\site-packages\flask_socketio\__init__.py", line 45, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "C:\Git\neighbors_server\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Git\neighbors_server\lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Git\neighbors_server\lib\site-packages\engineio\server.py", line 367, in handle_request
    r = self._handle_connect(environ, start_response,
  File "C:\Git\neighbors_server\lib\site-packages\engineio\server.py", line 519, in _handle_connect
    del self.sockets[sid]
KeyError: '8cff9af354854b37ad33b5e5d6689d4f'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Git\neighbors_server\lib\site-packages\eventlet\wsgi.py", line 357, in __init__
    self.handle()
  File "C:\Git\neighbors_server\lib\site-packages\eventlet\wsgi.py", line 390, in handle
    self.handle_one_request()
  File "C:\Git\neighbors_server\lib\site-packages\eventlet\wsgi.py", line 466, in handle_one_request
    self.handle_one_response()
  File "C:\Git\neighbors_server\lib\site-packages\eventlet\wsgi.py", line 609, in handle_one_response
    write(err_body)
  File "C:\Git\neighbors_server\lib\site-packages\eventlet\wsgi.py", line 538, in write
    wfile.flush()
  File "D:\Python38\lib\socket.py", line 687, in write
    return self._sock.send(b)
  File "C:\Git\neighbors_server\lib\site-packages\eventlet\greenio\base.py", line 397, in send
    return self._send_loop(self.fd.send, data, flags)
  File "C:\Git\neighbors_server\lib\site-packages\eventlet\greenio\base.py", line 384, in _send_loop
    return send_method(data, *args)
BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Git\neighbors_server\lib\site-packages\eventlet\hubs\selects.py", line 59, in wait
    listeners.get(fileno, hub.noop).cb(fileno)
  File "C:\Git\neighbors_server\lib\site-packages\eventlet\greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "C:\Git\neighbors_server\lib\site-packages\eventlet\wsgi.py", line 818, in process_request
    proto.__init__(conn_state, self)
  File "C:\Git\neighbors_server\lib\site-packages\eventlet\wsgi.py", line 359, in __init__
    self.finish()
  File "C:\Git\neighbors_server\lib\site-packages\eventlet\wsgi.py", line 732, in finish
    BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "D:\Python38\lib\socketserver.py", line 784, in finish
    self.wfile.close()
  File "D:\Python38\lib\socket.py", line 687, in write
    return self._sock.send(b)
  File "C:\Git\neighbors_server\lib\site-packages\eventlet\greenio\base.py", line 397, in send
    return self._send_loop(self.fd.send, data, flags)
  File "C:\Git\neighbors_server\lib\site-packages\eventlet\greenio\base.py", line 384, in _send_loop
    return send_method(data, *args)
BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call
Removing descriptor: 596
```

**Comment by miguelgrinberg** [comment]
Why did you write a new issue if the PR addresses the problem? Or is there any additional problem that the PR does not address for you?

**Comment by arbel03** [comment]
I Saw the PR after I opened the issue, in any case, the PR includes only a small one line change.
Would be grateful if it can be merged soon. thanks
