### ISSUE TITLE
"Client is gone, closing socket"

### ISSUE THREAD

**Issue by tavurth** [miguelgrinberg/python-engineio#19]
I'm running python 2.7, and using gevent for the middleware.

I've been running into an intermittent problem, which only seems to occur when the client-side application is in an open browser window, and the tab is not being shown.

Gevent has been monkey-patched, and the patching is the first operation of the server. 
Application is here: http://tavurth.bshellz.net

The code shown is python-engineio logging information:
```
5f98baf792624dfabfc01011800bda7e: Received packet PING data None
5f98baf792624dfabfc01011800bda7e: Sending packet PONG data None
"GET /v1/************************************************** HTTP/1.1" 200 None
ca69858d47244650b2a10945976324cd: Client is gone, closing socket
```

The code listed below is what is shown in the normal logging of python-engineio:
```
Traceback (most recent call last):
  File "/home/tavurth/.local/lib/python2.7/site-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "/home/tavurth/.local/lib/python2.7/site-packages/gevent/pywsgi.py", line 494, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/home/tavurth/.local/lib/python2.7/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/tavurth/.local/lib/python2.7/site-packages/socketio/server.py", line 303, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/tavurth/.local/lib/python2.7/site-packages/engineio/server.py", line 242, in handle_request
    socket = self._get_socket(sid)
  File "/home/tavurth/.local/lib/python2.7/site-packages/engineio/server.py", line 340, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
{'CONTENT_LENGTH': '3',
 'CONTENT_TYPE': 'text/plain;charset=UTF-8',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_COOKIE': 'io=c6e91c99f271419283b91068c297bccc',
 'HTTP_HOST': 'IP_ADDR_HIDDEN:9000',
 'HTTP_ORIGIN': 'http://HTTP_ORIGIN_HIDDEN',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_REFERER': 'http://HTTP_ORIGIN_HIDDEN/CServer/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2550.0 Iron/48.0.2550.0 Safari/537.36',
 'PATH_INFO': '/socket.io/',
 'QUERY_STRING': 'EIO=3&transport=polling&t=LGwzkIs&sid=c6e91c99f271419283b91068c297bccc',
 'REMOTE_ADDR': 'REMOTE_ADDR_HIDDEN',
 'REMOTE_PORT': '16576',
 'REQUEST_METHOD': 'POST',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'SERVER_HIDDEN',
 'SERVER_PORT': '9000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x72ff488d0270>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x36b5fd0>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with KeyError

REMOTE_ADDR_HIDDEN - - [2016-04-22 00:36:37] "POST /socket.io/?EIO=3&transport=polling&t=LGwzkIs&sid=c6e91c99f271419283b91068c297bccc HTTP/1.1" 500 161 0.002151
REMOTE_ADDR_HIDDEN - - [2016-04-22 00:36:37] "POST /socket.io/?EIO=3&transport=polling&t=LGwzkKl&sid=c6e91c99f271419283b91068c297bccc HTTP/1.1" 400 219 0.000296
2016-04-22 00:36:38.512355 ------------------------- CONNECT -------------------------
```

The error messages that are shown in the browsers console:
```
socket.io.js:1 POST http://IP_ADDR_HIDDEN:9000/socket.io/?EIO=3&transport=polling&t=LGwzkIs&sid=c6e91c99f271419283b91068c297bccc Request.create @ socket.io.js:1Request @ socket.io.js:1XHR.request @ socket.io.js:1XHR.doWrite @ socket.io.js:1(anonymous function) @ socket.io.js:1(anonymous function) @ socket.io.js:2proxy @ socket.io.js:1(anonymous function) @ socket.io.js:2(anonymous function) @ socket.io.js:2exports.encodePacket @ socket.io.js:2encodeOne @ socket.io.js:2eachWithIndex @ socket.io.js:2map @ socket.io.js:2exports.encodePayload @ socket.io.js:2Polling.write @ socket.io.js:1Transport.send @ socket.io.js:1Socket.flush @ socket.io.js:1Socket.sendPacket @ socket.io.js:1Socket.ping @ socket.io.js:1(anonymous function) @ socket.io.js:1
(index):1 XMLHttpRequest cannot load http://IP_ADDR_HIDDEN:9000/socket.io/?EIO=3&transport=polling&t=LGwzkIs&sid=c6e91c99f271419283b91068c297bccc. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://HTTP_ORIGIN_HIDDEN' is therefore not allowed access. The response had HTTP status code 500.
compiled.js:344 Normal error:Error: xhr post error
compiled.js:2972 Disconnect: transport error
```

With full socketio logging enabled (client-side):
```
engine.io-client:polling-xhr xhr open POST: http://REMOTE_ADDR_HIDDEN:9000/socket.io/?EIO=3&transport=polling&t=LGw-MVP&sid=0d697a561caf43969835747522b04941 +1ms
socket.io.js:2 engine.io-client:polling-xhr xhr data 1:2 +0ms
socket.io.js:2 engine.io-client:polling polling got data ArrayBuffer +82ms
socket.io.js:2 engine.io-client:socket socket receive: type "pong", data "undefined" +2ms
socket.io.js:2 engine.io-client:polling polling +1ms
socket.io.js:2 engine.io-client:polling-xhr xhr poll +1ms
socket.io.js:2 engine.io-client:polling-xhr xhr open GET: http://REMOTE_ADDR_HIDDEN:8888/socket.io/?EIO=3&transport=polling&t=LGw-MWl&sid=89ffe28ca55147478045843ba1036a50 +0ms
socket.io.js:2 engine.io-client:polling-xhr xhr data null +1ms
socket.io.js:2 engine.io-client:polling polling got data ArrayBuffer +3ms
socket.io.js:2 engine.io-client:socket socket receive: type "pong", data "undefined" +2ms
socket.io.js:2 engine.io-client:polling polling +1ms
socket.io.js:2 engine.io-client:polling-xhr xhr poll +0ms
socket.io.js:2 engine.io-client:polling-xhr xhr open GET: http://REMOTE_ADDR_HIDDEN:9000/socket.io/?EIO=3&transport=polling&t=LGw-MWs&sid=0d697a561caf43969835747522b04941 +1ms
socket.io.js:2 engine.io-client:polling-xhr xhr data null +0ms
socket.io.js:2 engine.io-client:socket writing ping packet - expecting pong within 300000ms +29s
socket.io.js:2 engine.io-client:socket flushing 1 packets in socket +0ms
socket.io.js:2 engine.io-client:polling-xhr xhr open POST: http://REMOTE_ADDR_HIDDEN:8888/socket.io/?EIO=3&transport=polling&t=LGw-Tdy&sid=89ffe28ca55147478045843ba1036a50 +1ms
socket.io.js:2 engine.io-client:polling-xhr xhr data 1:2 +1ms
socket.io.js:2 engine.io-client:socket writing ping packet - expecting pong within 300000ms +2ms
socket.io.js:2 engine.io-client:socket flushing 1 packets in socket +1ms
socket.io.js:2 engine.io-client:polling-xhr xhr open POST: http://REMOTE_ADDR_HIDDEN:9000/socket.io/?EIO=3&transport=polling&t=LGw-Te0&sid=0d697a561caf43969835747522b04941 +0ms
socket.io.js:2 engine.io-client:polling-xhr xhr data 1:2 +2ms
socket.io.js:1 POST http://REMOTE_ADDR_HIDDEN:9000/socket.io/?EIO=3&transport=polling&t=LGw-Te0&sid=0d697a561caf43969835747522b04941 Request.create @ socket.io.js:1Request @ socket.io.js:1XHR.request @ socket.io.js:1XHR.doWrite @ socket.io.js:1(anonymous function) @ socket.io.js:1(anonymous function) @ socket.io.js:2proxy @ socket.io.js:1(anonymous function) @ socket.io.js:2(anonymous function) @ socket.io.js:2exports.encodePacket @ socket.io.js:2encodeOne @ socket.io.js:2eachWithIndex @ socket.io.js:2map @ socket.io.js:2exports.encodePayload @ socket.io.js:2Polling.write @ socket.io.js:1Transport.send @ socket.io.js:1Socket.flush @ socket.io.js:1Socket.sendPacket @ socket.io.js:1Socket.ping @ socket.io.js:1(anonymous function) @ socket.io.js:1
(index):1 XMLHttpRequest cannot load http://REMOTE_ADDR_HIDDEN:9000/socket.io/?EIO=3&transport=polling&t=LGw-Te0&sid=0d697a561caf43969835747522b04941. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://SERVER_ADDR_HIDDEN' is therefore not allowed access. The response had HTTP status code 500.
socket.io.js:2 engine.io-client:polling polling got data ArrayBuffer +61ms
socket.io.js:2 engine.io-client:socket socket receive: type "pong", data "undefined" +1ms
socket.io.js:2 engine.io-client:polling polling +1ms
socket.io.js:2 engine.io-client:polling-xhr xhr poll +0ms
socket.io.js:2 engine.io-client:polling-xhr xhr open GET: http://REMOTE_ADDR_HIDDEN:8888/socket.io/?EIO=3&transport=polling&t=LGw-Tf2&sid=89ffe28ca55147478045843ba1036a50 +1ms
socket.io.js:2 engine.io-client:polling-xhr xhr data null +1ms
socket.io.js:2 engine.io-client:socket socket error {"type":"TransportError","description":0} +10s
socket.io.js:2 socket.io-client:manager error +50s Error: xhr post error(…)
compiled.js:344 Normal error:Error: xhr post error
socket.io.js:2 engine.io-client:socket socket close with reason: "transport error" +7ms
socket.io.js:2 engine.io-client:polling transport open - closing +0ms
socket.io.js:2 engine.io-client:polling writing close packet +1ms
socket.io.js:2 engine.io-client:polling-xhr xhr open POST: http://REMOTE_ADDR_HIDDEN:9000/socket.io/?EIO=3&transport=polling&t=LGw-WDD&sid=0d697a561caf43969835747522b04941 +1ms
socket.io.js:2 engine.io-client:polling-xhr xhr data 1:1 +1ms
socket.io.js:2 socket.io-client:manager onclose +11ms
socket.io.js:2 socket.io-client:manager cleanup +1ms
socket.io.js:2 socket.io-client:socket close (transport error) +1ms
compiled.js:2972 Disconnect: transport error
socket.io.js:2 socket.io-client:manager will wait 1054ms before reconnect attempt +1ms
socket.io.js:1 POST http://REMOTE_ADDR_HIDDEN:9000/socket.io/?EIO=3&transport=polling&t=LGw-WDD&sid=0d697a561caf43969835747522b04941 400 (BAD REQUEST)Request.create @ socket.io.js:1Request @ socket.io.js:1XHR.request @ socket.io.js:1XHR.doWrite @ socket.io.js:1(anonymous function) @ socket.io.js:1(anonymous function) @ socket.io.js:2proxy @ socket.io.js:1(anonymous function) @ socket.io.js:2(anonymous function) @ socket.io.js:2exports.encodePacket @ socket.io.js:2encodeOne @ socket.io.js:2eachWithIndex @ socket.io.js:2map @ socket.io.js:2exports.encodePayload @ socket.io.js:2Polling.write @ socket.io.js:1close @ socket.io.js:1Polling.doClose @ socket.io.js:1Transport.close @ socket.io.js:1Socket.onClose @ socket.io.js:1Socket.onError @ socket.io.js:1(anonymous function) @ socket.io.js:1Emitter.emit @ socket.io.js:2Transport.onError @ socket.io.js:1(anonymous function) @ socket.io.js:1Emitter.emit @ socket.io.js:2Request.onError @ socket.io.js:1(anonymous function) @ socket.io.js:1
socket.io.js:2 socket.io-client:manager attempting reconnect +1s
socket.io.js:2 socket.io-client:manager readyState closed +1ms
```

Does anyone have any ideas?

Kind regards,
Will

**Comment by miguelgrinberg** [comment]
Your application appears to create two socket connections, not one. Is there a reason for that? And it uses long polling, not websocket. These are not bugs, but I thought I'd mention it because they are not something you would expect.

As far as the errors, it would be useful to run the server in debug mode, so that you can see stack traces when an error occurs.

**Comment by tavurth** [comment]
Thank you for getting back to me so quickly!

Yes, I decided to split my process, as I intend to build on the user interface, while leaving data transfer as stable and multi purpose as possible. (Likely later moved to a separate server)

I've changed the server backend to run on Gevent websockets, I'll leave it running for some time to see how it's handling the requests.

**Comment by tavurth** [comment]
After changing to Websockets the socket stays open a similar amount of time, and then closes with this error (Browser):
```
engine.io-client:socket writing ping packet - expecting pong within 300000ms +24s
socket.io.js:2 engine.io-client:socket flushing 1 packets in socket +1ms
socket.io.js:2 engine.io-client:socket writing ping packet - expecting pong within 300000ms +0ms
socket.io.js:2 engine.io-client:socket flushing 1 packets in socket +1ms
socket.io.js:2 engine.io-client:socket socket receive: type "pong", data "undefined" +52ms
socket.io.js:2 engine.io-client:socket socket close with reason: "transport close" +98ms
socket.io.js:2 socket.io-client:manager onclose +24s
socket.io.js:2 socket.io-client:manager cleanup +0ms
socket.io.js:2 socket.io-client:socket close (transport close) +1ms
compiled.js:19 Disconnect: transport close
socket.io.js:2 socket.io-client:manager will wait 863ms before reconnect attempt +2ms
socket.io.js:2 socket.io-client:manager attempting reconnect +2s
socket.io.js:2 socket.io-client:manager readyState closed +1ms
```

From the server side, I see the following:
```
7e64d3eac4154dad9c27b93f8e7ad8e4: Client is gone, closing socket
7e64d3eac4154dad9c27b93f8e7ad8e4: Received packet PING data None
Closed WebSocket
Initializing WebSocket
Validating WebSocket request
dfc7a0f9916a42cbb3fbafc375c466ec: Sending packet OPEN data {'pingInterval': 20000, 'pingTimeout': 300000, 'upgrades': ['websocket'], 'sid': 'dfc7a0f9916a42cbb3fbafc375c466ec'}
dfc7a0f9916a42cbb3fbafc375c466ec: Sending packet MESSAGE data 0
IP_ADDR_HIDDEN - - [2016-04-22 01:54:30] "GET /socket.io/?EIO=3&transport=polling&t=LGxFZEc HTTP/1.1" 200 383 0.000691
Initializing WebSocket
Validating WebSocket request
Can only upgrade connection if using GET method.
dfc7a0f9916a42cbb3fbafc375c466ec: Received packet MESSAGE data 2["heartbeat"]
received event "heartbeat" from dfc7a0f9916a42cbb3fbafc375c466ec [/]
IP_ADDR_HIDDEN - - [2016-04-22 01:54:30] "POST /socket.io/?EIO=3&transport=polling&t=LGxFZFo&sid=dfc7a0f9916a42cbb3fbafc375c466ec HTTP/1.1" 200 200 0.000532
Initializing WebSocket
Validating WebSocket request
Attempting to upgrade connection
WebSocket request accepted, switching protocols
dfc7a0f9916a42cbb3fbafc375c466ec: Received request to upgrade to websocket
Initializing WebSocket
Validating WebSocket request
dfc7a0f9916a42cbb3fbafc375c466ec: Sending packet NOOP data None
```

Perhaps I'm doing something wrong somewhere, and forcing a disconnect event although I don't think so. I'll try to find the time for a simplified version this weekend.

**Comment by miguelgrinberg** [comment]
What client are you using?

**Comment by tavurth** [comment]
So I've checked it again using Chromium and Opera, seems to be working fine now, although the problem was intermittent.

Thank you for the architectural advice, I originally split the server as I plan on performing some serious statistical number crunching, and didn't want it to slow down client interaction, sharing etc.
I was thinking of hosting a dedicated server for such work.

Is it very bad practice to have more than one open socket connection?

**Comment by miguelgrinberg** [comment]
> Is it very bad practice to have more than one open socket connection?

It's not bad practice, it's just inefficient. The Socket.IO protocol provides namespaces specifically to address that need by multiplexing multiple logical connections on a single physical channel.

**Comment by tavurth** [comment]
I've added a workaround so that events re-authenticate if the client drops the connection, should be more robust in most cases.

Thanks for the explanation, and for your help!
