### ISSUE TITLE
Troubleshoot Session is Disconnected

### ISSUE THREAD

**Issue by croxis** [miguelgrinberg/python-engineio#2]
I'm using engineio through the flask-socketio library. I'm not sure which library is the culprit -- I'll start here :). 

I have a long running process I'm running via POpen with readline() executed in a separate thread. The output is being sent to the client browser with socketio. I thought sockets might be closing from readline blocking the main thread, but moving it to its own thread has not resolved the issue.

Here is the traceback, 

```
DEBUG:app:Card generation complete.
Traceback (most recent call last):
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/engineio/middleware.py", line 32, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/socketio/server.py", line 286, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/engineio/server.py", line 232, in handle_request
    socket.handle_post_request(environ)
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/engineio/socket.py", line 89, in handle_post_request
    self.receive(pkt)
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/engineio/socket.py", line 44, in receive
    self.server._trigger_event('message', self.sid, pkt.data)
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/engineio/server.py", line 287, in _trigger_event
    return self.handlers[event](*args)
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/socketio/server.py", line 432, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/socketio/server.py", line 352, in _handle_event
    r = self._trigger_event(data[0], namespace, sid, *data[1:])
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/socketio/server.py", line 379, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/flask_socketio/__init__.py", line 80, in _handler
    self.server.environ[sid]['saved_session'] = {}
KeyError: '793664041a1b40b48ad47150445f55a9'
Traceback (most recent call last):
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/engineio/middleware.py", line 32, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/socketio/server.py", line 286, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/engineio/server.py", line 230, in handle_request
    socket = self._get_socket(sid)
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/engineio/server.py", line 297, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'

(This shows up after a few moments)
Traceback (most recent call last):
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/engineio/middleware.py", line 32, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/socketio/server.py", line 286, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/engineio/server.py", line 223, in handle_request
    del self.sockets[sid]
KeyError: '793664041a1b40b48ad47150445f55a9'
```

**Comment by miguelgrinberg** [comment]
You should be using eventlet or gevent for this type of application. You can't have any blocking calls (such as the reads from the pipe) during the handling of a request. To make this I/O calls non-blocking you should use the monkey patching function in either of the frameworks.

**Comment by croxis** [comment]
That fixed it! Thank you for pointing me on the right path.
