### ISSUE TITLE
Version: 3.14.1 Incompatible python2

### ISSUE THREAD

**Issue by divmid** [miguelgrinberg/python-engineio#202]
```
(py2) [root@localhost ~]# pip show python-engineio
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Name: python-engineio
Version: 3.14.1
Summary: Engine.IO server
Home-page: http://github.com/miguelgrinberg/python-engineio/
Author: Miguel Grinberg
Author-email: miguelgrinberg50@gmail.com
License: MIT
Location: /home/vackbot/venvs/py2/lib/python2.7/site-packages
Requires: six
Required-by: python-socketio
(py2) [root@localhost vackbot]# python
Python 2.7.5 (default, Apr  2 2020, 13:16:51) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

```
(py2) [root@localhost ~]# gunicorn -c python:api.config.gunicorn api.init:api --preload
Traceback (most recent call last):
  File "/home/vackbot/venvs/py2/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/home/vackbot/venvs/py2/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/vackbot/venvs/py2/lib/python2.7/site-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/home/vackbot/venvs/py2/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/vackbot/venvs/py2/lib/python2.7/site-packages/gunicorn/arbiter.py", line 60, in __init__
    self.setup(app)
  File "/home/vackbot/venvs/py2/lib/python2.7/site-packages/gunicorn/arbiter.py", line 120, in setup
    self.app.wsgi()
  File "/home/vackbot/venvs/py2/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/vackbot/venvs/py2/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/vackbot/venvs/py2/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/vackbot/venvs/py2/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/vackbot/venvs/py2/lib/python2.7/site-packages/api/init.py", line 39, in <module>
    from api.websockets.message import MessageNamespace
  File "/home/vackbot/venvs/py2/lib/python2.7/site-packages/api/websockets/message.py", line 3, in <module>
    from flask_socketio import emit
  File "/home/vackbot/venvs/py2/lib/python2.7/site-packages/flask_socketio/__init__.py", line 16, in <module>
    import socketio
  File "/home/vackbot/venvs/py2/lib/python2.7/site-packages/socketio/__init__.py", line 3, in <module>
    from .client import Client
  File "/home/vackbot/venvs/py2/lib/python2.7/site-packages/socketio/client.py", line 7, in <module>
    import engineio
  File "/home/vackbot/venvs/py2/lib/python2.7/site-packages/engineio/__init__.py", line 3, in <module>
    from .client import Client
  File "/home/vackbot/venvs/py2/lib/python2.7/site-packages/engineio/client.py", line 2, in <module>
    from json import JSONDecodeError
ImportError: cannot import name JSONDecodeError
(py2) [root@localhost ~]# vim  /home/vackbot/venvs/py2/lib/python2.7/site-packages/engineio/client.py
(py2) [root@localhost ~]# gunicorn -c python:api.config.gunicorn api.init:api --preload
> /home/vackbot/venvs/py2/lib/python2.7/site-packages/engineio/client.py(3)<module>()
-> from base64 import b64encode
(Pdb) import json 
(Pdb) dir(json)
['JSONDecoder', 'JSONEncoder', '__all__', '__author__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', '_default_decoder', '_default_encoder', 'decoder', 'dump', 'dumps', 'encoder', 'load', 'loads', 'scanner']
(Pdb) from json import JSONDecodeError
*** ImportError: cannot import name JSONDecodeError
```

* https://stackoverflow.com/questions/15170676/cannot-import-jsondecodeerror

**Comment by miguelgrinberg** [comment]
Python 2 is not supported.
