### ISSUE TITLE
[Unexpected Behaviour] Not handling ConnectionResetError in _write_loop in asyncio_client.py

### ISSUE THREAD

**Issue by Charles-YYH** [miguelgrinberg/python-engineio#208]
Hello, I've found an unexpected behaviour while playing with python-socketio client using websocket backend. After some investigation, I think this issue comes from engineio side.

## Steps to Reproduce
Given the following code snippet
```python
import socketio

async def main():
    sio = socketio.AsyncClient(logger=True, engineio_logger=True)
    await sio.connect('a web socket url')
    await asyncio.sleep(5)
    await sio.disconnect()
    await asyncio.sleep(1)

asyncio.run(main())
```

## Current Behavior
After calling the `sio.disconnect()`, I've got an untrieved task exception, stack trace below
```
Sending packet MESSAGE data 1
Sending packet CLOSE data None
Engine.IO connection dropped
Unexpected error receiving packet: "WebSocket read returned None", aborting
Waiting for write loop task to end
Exiting ping task
future: <Task finished name='Task-8' coro=<AsyncClient._read_loop_websocket() done, defined at /Users/yangyihui/Documents/.venv/VistoAdminServiceV2/lib/python3.8/site-packages/engineio/asyncio_client.py:520> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/lib/python3.8/site-packages/engineio/asyncio_client.py", line 551, in _read_loop_websocket
    await self.write_loop_task
  File "lib/python3.8/site-packages/engineio/asyncio_client.py", line 636, in _write_loop
    await self.ws.send_str(pkt.encode(
  File "/lib/python3.8/site-packages/aiohttp/client_ws.py", line 150, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 687, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 598, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```
## Possible Solution

According to the stack trace, a ConnectionResetError is not handled while closing the connection. This exception is threw by the websocket library while attempting writing a packet on a closing websocket.

An easy solution might be handling ConnectionResetError while sending packet. [asyncio_client.py](https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/asyncio_client.py#L602)

## Environment
python-engineio==3.13.2
python-socketio==4.6.0

**Comment by miguelgrinberg** [comment]
This error does not occur with the latest version of the Socket.IO client. Upgrade and retest to confirm please.

**Comment by Charles-YYH** [comment]
Thanks for your quick response,

I've upgraded the python-socketio version, and the problem remained. I need to fix the engineio version so that it's compatible with the server.

python-engineio==3.13.2
python-socketio==5.0.4

Here attached full log.

```
Attempting polling connection to http://some-url/socket.io/?transport=polling&EIO=3
Polling connection accepted with {'sid': 'nOgNhxzwMTmVQMd5AABi', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 5000}
Engine.IO connection established
Sending packet MESSAGE data 0
Received packet MESSAGE data 0
Attempting WebSocket upgrade to ws://some-url/socket.io/?transport=websocket&EIO=3
Namespace / is connected
WebSocket upgrade was successful
Sending packet PING data None
Received packet PONG data None
Sending packet MESSAGE data 1
Sending packet CLOSE data None
Engine.IO connection dropped
Unexpected error receiving packet: "WebSocket read returned None", aborting
Waiting for write loop task to end
Exiting ping task
Task exception was never retrieved
future: <Task finished name='Task-8' coro=<AsyncClient._read_loop_websocket() done, defined at /lib/python3.8/site-packages/engineio/asyncio_client.py:520> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/lib/python3.8/site-packages/engineio/asyncio_client.py", line 551, in _read_loop_websocket
    await self.write_loop_task
  File "/lib/python3.8/site-packages/engineio/asyncio_client.py", line 622, in _write_loop
    await self.ws.send_str(pkt.encode(
  File "/lib/python3.8/site-packages/aiohttp/client_ws.py", line 150, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 687, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 598, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

```

**Comment by miguelgrinberg** [comment]
You can't upgrade socketio and leave engineio on the old release. There is a version compatibility table in the docs, you can only combine versions that are compatible.

**Comment by Charles-YYH** [comment]
Thanks for pointing that out.

I will try upgrading to JavaScript Socket.IO version 3.x server side and upgrade both socketio and engineio to the newest version.
