### ISSUE TITLE
0.9.1 fix doesn't call disconnect handler when a client timeout

### ISSUE THREAD

**Issue by christopher-abastar** [miguelgrinberg/python-engineio#22]
Hi Miguel,

Thanks for this 0.9.1 fix, I believe this is for the issue I posted related to the thread handling redis dying when there was an error thrown.  After this fix has been added. It seems to be working well now but currently i'm encountering a different error.  I reduced the ping_interval = 2, or a very low number. For some reason, when a certain client timeouts (failed to receive ping/pong) the server doesn't handle the cleanup and go to the @disconnect handler. 

``` sh
WARNING in server [/home/vf/env/lib/python3.5/site-packages/engineio/server.py:161]:
Cannot send to sid 6552fc4cf4024c6f8b30e7a1bef308f1 - data 2["join_ok",{"room":"guild"}]
--------------------------------------------------------------------------------
--- Logging error ---
Traceback (most recent call last):
  File "/home/vf/env/lib/python3.5/site-packages/engineio/server.py", line 158, in send
    socket = self._get_socket(sid)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/server.py", line 345, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/logging/handlers.py", line 974, in emit
    smtp = smtplib.SMTP(self.mailhost, port, timeout=self.timeout)
  File "/usr/local/lib/python3.5/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.5/smtplib.py", line 335, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.5/smtplib.py", line 306, in _get_socket
    self.source_address)
  File "/home/vf/env/lib/python3.5/site-packages/eventlet/green/socket.py", line 63, in create_connection
    raise err
  File "/home/vf/env/lib/python3.5/site-packages/eventlet/green/socket.py", line 53, in create_connection
    sock.connect(sa)
  File "/home/vf/env/lib/python3.5/site-packages/eventlet/greenio/base.py", line 244, in connect
    if socket_connect(fd, address):
  File "/home/vf/env/lib/python3.5/site-packages/eventlet/greenio/base.py", line 37, in socket_connect
    raise socket.error(err, errno.errorcode[err])
ConnectionRefusedError: [Errno 61] ECONNREFUSED
Call stack:
  File "/home/vf/env/lib/python3.5/site-packages/eventlet/green/thread.py", line 41, in __thread_body
    func(*args, **kwargs)
  File "/usr/local/lib/python3.5/threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File "/home/vf/env/lib/python3.5/site-packages/eventlet/green/thread.py", line 62, in wrap_bootstrap_inner
    bootstrap_inner()
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vf/env/lib/python3.5/site-packages/socketio/pubsub_manager.py", line 143, in _thread
    self._handle_emit(data)
  File "/home/vf/env/lib/python3.5/site-packages/socketio/pubsub_manager.py", line 101, in _handle_emit
    callback=callback)
  File "/home/vf/env/lib/python3.5/site-packages/socketio/base_manager.py", line 106, in emit
    self.server._emit_internal(sid, event, data, namespace, id)
  File "/home/vf/env/lib/python3.5/site-packages/socketio/server.py", line 325, in _emit_internal
    binary=binary))
  File "/home/vf/env/lib/python3.5/site-packages/socketio/server.py", line 336, in _send_packet
    self.eio.send(sid, encoded_packet, binary=False)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/server.py", line 161, in send
    self.logger.warning('Cannot send to sid {} - data {}'.format(sid, data))
Message: 'Cannot send to sid 6552fc4cf4024c6f8b30e7a1bef308f1 - data 2["join_ok",{"room":"guild"}]'

```

**Comment by christopher-abastar** [comment]
Hello miguel,

After looking to some possible scenarios, i think i found something here. It only happens on a redis backend for the a certain background process to emit.  

Whenever a client is disconnected or timing out because of no ping/pong response, then here comes a delayed emit from the background process, it tries to send to the 'sid' that was disconnected. Then it dies because the socket is not there.

Here is the code from the socket.io/server.py

```python
 def _emit_internal(self, sid, event, data, namespace=None, id=None):
     """Send a message to a client."""
     if six.PY2 and not self.binary:
         binary = False  # pragma: nocover
     else:
         binary = None
     # tuples are expanded to multiple arguments, everything else is sent
     # as a single argument
     if isinstance(data, tuple):
         data = list(data)
     else:
         data = [data]
     self._send_packet(sid, packet.Packet(packet.EVENT, namespace=namespace,
                                          data=[event] + data, id=id,
                                          binary=binary))

```

Should we have something like:
```python
def _emit_internal(self, sid, event, data, namespace=None, id=None):
     """Send a message to a client."""
     if six.PY2 and not self.binary:
         binary = False  # pragma: nocover
     else:
         binary = None
     # tuples are expanded to multiple arguments, everything else is sent
     # as a single argument
     if isinstance(data, tuple):
         data = list(data)
     else:
         data = [data]
         try:
             self._send_packet(sid, packet.Packet(packet.EVENT, namespace=namespace,
                                          data=[event] + data, id=id,
                                          binary=binary))
         except:
             self._handle_disconnect(sid,namespace)
```


This should catch bad sending of packets and doesn't let the thread die handling the redis pub/sub events?

**Comment by miguelgrinberg** [comment]
@christopher-abastar Have you verified that this actually helps? I'm not sure it does. The `_send_packet()` method will eventually call the `send()` method in engineio's `Server` class. And in that method you can see that there is a check to ensure the socket is available before anything is sent.

**Comment by christopher-abastar** [comment]
hi @miguelgrinberg ,

I'm still running some tests on it, yes i see from v0.9.1 the warning has been added below.

```python
 def send(self, sid, data, binary=None):
     """Send a message to a client.

     :param sid: The session id of the recipient client.
     :param data: The data to send to the client. Data can be of type
                  ``str``, ``bytes``, ``list`` or ``dict``. If a ``list``
                  or ``dict``, the data will be serialized as JSON.
     :param binary: ``True`` to send packet as binary, ``False`` to send
                    as text. If not given, unicode (Python 2) and str
                    (Python 3) are sent as text, and str (Python 2) and
                    bytes (Python 3) are sent as binary.
     """
     try:
         socket = self._get_socket(sid)
     except KeyError:
         # the socket is not available
         self.logger.warning('Cannot send to sid %s', sid)
         return
     socket.send(packet.Packet(packet.MESSAGE, data=data, binary=binary))
```

After the try/except added, I was encountering some problems wherein the disconnect handler from my app are not being called properly. Some session variables were still there and had to restart the server to clear those things up. 

However, I'll need to remove the 'return' upon keyerror to make sure the cleanup is done.

**Comment by christopher-abastar** [comment]
hello @miguelgrinberg,

I manage to test this implementation instead on the socketio/server.py

```python
def _emit_internal(self, sid, event, data, namespace=None, id=None):
    """Send a message to a client."""
    if six.PY2 and not self.binary:
        binary = False  # pragma: nocover
    else:
        binary = None
    # tuples are expanded to multiple arguments, everything else is sent
    # as a single argument
    if isinstance(data, tuple):
        data = list(data)
    else:
        data = [data]
    try:
        self._send_packet(sid, packet.Packet(packet.EVENT, namespace=namespace,
                                             data=[event] + data, id=id,
                                             binary=binary))
    except:
        self.logger.error('error in _emit_internal %s', sid)
        self._trigger_event('disconnect', namespace, sid)
        self.manager.disconnect(sid, namespace=namespace)
```

It can properly call the disconnect handler without killing the thread handling the redis. Will keep a close eye on it for a couple of days.

**Comment by christopher-abastar** [comment]
hi @miguelgrinberg,

After adding the fix above, it was able to manage the disconnects properly and not kill the thread handling redis.  I already received a couple of errors in the server when this happens and managed NOT to restart it anymore.

**Comment by christopher-abastar** [comment]
hi @miguelgrinberg ,

2 Weeks of testing and observation I managed to stabilize the servers with the following fix:

```python
    def _emit_internal(self, sid, event, data, namespace=None, id=None):
        """Send a message to a client."""
        if six.PY2 and not self.binary:
            binary = False  # pragma: nocover
        else:
            binary = None
        # tuples are expanded to multiple arguments, everything else is sent
        # as a single argument
        if isinstance(data, tuple):
            data = list(data)
        else:
            data = [data]

        try:
            self._send_packet(sid, packet.Packet(packet.EVENT, namespace=namespace,
                                                 data=[event] + data, id=id,
                                                 binary=binary))
        except:
            self.logger.error('error in _emit_internal %s', sid)
            try:
                self._trigger_event('disconnect', namespace, sid)
                self.manager.disconnect(sid, namespace=namespace)
            except:
                self.logger.error('error in _emit_internal cleanup %s', sid)
                pass
```

It just happens that there were two different cases of happening.   One case, was the send_packet not able to send due to sid is not available, and after doing the cleanup of the event handler some response are successful but others were throwing errors on the cleanup process.  I just added a try catch on the cleanup process to allow.

**Comment by miguelgrinberg** [comment]
@christopher-abastar do you have the stack trace of the error you are catching with your changes?

**Comment by christopher-abastar** [comment]
Here's an example miguel:


##  Before Changes 

Please do note I removed the 'return' statement to force the error: 
`
  File "/home/vf/env/lib/python3.5/site-packages/engineio/server.py", line 161, in send
    raise KeyError('Cannot send to sid %s', sid)
`

```
4d6e1a23978849a4a87a652df11053d6: Received packet MESSAGE data 2["join",{"room":"guild"}]
4d6e1a23978849a4a87a652df11053d6: Client is gone, closing socket
--------------------------------------------------------------------------------
INFO in connect [/usr/home/vf/releases/20160714013348/gameapp/app/socket/connect.py:59]:
Number of clients: 6
--------------------------------------------------------------------------------
4d6e1a23978849a4a87a652df11053d6: Received packet MESSAGE data 2["join",{"room":"world","channel":2,"lang":"general"}]
Traceback (most recent call last):
  File "/home/vf/env/lib/python3.5/site-packages/eventlet/wsgi.py", line 454, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/home/vf/env/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vf/env/lib/python3.5/site-packages/flask_socketio/__init__.py", line 37, in __call__
    start_response)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/vf/env/lib/python3.5/site-packages/socketio/server.py", line 306, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/server.py", line 221, in handle_request
    transport, b64)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/server.py", line 325, in _handle_connect
    return s.handle_get_request(environ, start_response)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/socket.py", line 80, in handle_get_request
    start_response)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/socket.py", line 119, in _upgrade_websocket
    return ws(environ, start_response)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/async_eventlet.py", line 14, in __call__
    return super(WebSocketWSGI, self).__call__(environ, start_response)
  File "/home/vf/env/lib/python3.5/site-packages/eventlet/websocket.py", line 127, in __call__
    self.handler(ws)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/socket.py", line 181, in _websocket_handler
    self.receive(pkt)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/socket.py", line 49, in receive
    async=False)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/server.py", line 348, in _trigger_event
    return self.handlers[event](*args)
  File "/home/vf/env/lib/python3.5/site-packages/socketio/server.py", line 438, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/home/vf/env/lib/python3.5/site-packages/socketio/server.py", line 380, in _handle_event
    r = self._trigger_event(data[0], namespace, sid, *data[1:])
  File "/home/vf/env/lib/python3.5/site-packages/socketio/server.py", line 406, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/home/vf/env/lib/python3.5/site-packages/flask_socketio/__init__.py", line 177, in _handler
    app = self.server.environ[sid]['flask.app']
KeyError: '4d6e1a23978849a4a87a652df11053d6'
```

```ascii
error in _emit_internal 4d6e1a23978849a4a87a652df11053d6
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/vf/env/lib/python3.5/site-packages/engineio/server.py", line 158, in send
    socket = self._get_socket(sid)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/server.py", line 358, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vf/env/lib/python3.5/site-packages/socketio/server.py", line 327, in _emit_internal
    binary=binary))
  File "/home/vf/env/lib/python3.5/site-packages/socketio/server.py", line 342, in _send_packet
    self.eio.send(sid, encoded_packet, binary=False)
  File "/home/vf/env/lib/python3.5/site-packages/engineio/server.py", line 161, in send
    raise KeyError('Cannot send to sid %s', sid)
KeyError: ('Cannot send to sid %s', '4d6e1a23978849a4a87a652df11053d6')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vf/env/lib/python3.5/site-packages/socketio/pubsub_manager.py", line 143, in _thread
    self._handle_emit(data)
  File "/home/vf/env/lib/python3.5/site-packages/socketio/pubsub_manager.py", line 101, in _handle_emit
    callback=callback)
  File "/home/vf/env/lib/python3.5/site-packages/socketio/base_manager.py", line 106, in emit
    self.server._emit_internal(sid, event, data, namespace, id)
  File "/home/vf/env/lib/python3.5/site-packages/socketio/server.py", line 330, in _emit_internal
    self._trigger_event('disconnect', namespace, sid)
  File "/home/vf/env/lib/python3.5/site-packages/socketio/server.py", line 406, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/home/vf/env/lib/python3.5/site-packages/flask_socketio/__init__.py", line 177, in _handler
    app = self.server.environ[sid]['flask.app']
KeyError: '4d6e1a23978849a4a87a652df11053d6'

```


### After changes

```ascii
INFO in socket [/home/vf/env/lib/python3.5/site-packages/engineio/socket.py:43]:
b06569f7db564846b7c665ba683ae5cd: Received packet MESSAGE data 2["authenticate",""]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in connect [/usr/home/vf/releases/20160714013348/gameapp/app/socket/connect.py:73]:
Active Users: {'8e1d106c183d4ca1a295b2e0c9320c7d': '800788ca-44ce-460e-b754-d33995f7a175', '0059c762f644440cbc312c54e8b239d1': 'cafc7c86-60ce-4a68-b090-b8d0d6665084', '606201f2e8004ee08872576d913085ec': '7554963d-91ed-4a84-a9aa-d8d126d04f03', '1be3a5afe2614846909119719c2c
37de': '6c999975-c954-48f9-8c7b-04809f79280e', 'b06569f7db564846b7c665ba683ae5cd': '03b3e18c-84a2-44b9-a1bf-c9708522e68f'}
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in socket [/home/vf/env/lib/python3.5/site-packages/engineio/socket.py:68]:
b06569f7db564846b7c665ba683ae5cd: Sending packet MESSAGE data 2["auth_ok",1]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in socket [/home/vf/env/lib/python3.5/site-packages/engineio/socket.py:43]:
b06569f7db564846b7c665ba683ae5cd: Received packet MESSAGE data 2["join",{"room":"guild"}]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in socket [/home/vf/env/lib/python3.5/site-packages/engineio/socket.py:61]:
b06569f7db564846b7c665ba683ae5cd: Client is gone, closing socket
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in connect [/usr/home/vf/releases/20160714013348/gameapp/app/socket/connect.py:59]:
Number of clients: 4
```

Then after some time... 

```
--------------------------------------------------------------------------------
error in _emit_internal b06569f7db564846b7c665ba683ae5cd
error in _emit_internal cleanup b06569f7db564846b7c665ba683ae5cd
--------------------------------------------------------------------------------
```

Other errors not happening in cleanup

```
--------------------------------------------------------------------------------
error in _emit_internal 17b7b13dc7c14ea7b293aaea3470480a
--------------------------------------------------------------------------------
INFO in connect [/usr/home/vf/releases/20160714013348/gameapp/app/socket/connect.py:59]:
Number of clients: 6
--------------------------------------------------------------------------------
error in _emit_internal 2d6b43106b6146ed9c0bcfc458e00a7c
--------------------------------------------------------------------------------
INFO in connect [/usr/home/vf/releases/20160714013348/gameapp/app/socket/connect.py:59]:
Number of clients: 6
--------------------------------------------------------------------------------
```

**Comment by miguelgrinberg** [comment]
I believe I have addressed all errors regarding to leaks and missing the disconnect handler. Please reopen if you find problems with the current release.
