### ISSUE TITLE
KeyError: 'Session is disconnected' when restarting the aiohttp server with socket io

### ISSUE THREAD

**Issue by shasan-beanfield** [miguelgrinberg/python-engineio#241]
**Describe the bug**
A clear and concise description of what the bug is. If you are getting errors, please include the complete error message, including the stack trace.

Traceback (most recent call last):
  File "/opt/beanfield/beanmachine/venvs/beanmachine/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/opt/beanfield/beanmachine/venvs/beanmachine/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/opt/beanfield/beanmachine/venvs/beanmachine/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/opt/beanfield/beanmachine/venvs/beanmachine/lib/python3.6/site-packages/engineio/asyncio_server.py", line 249, in handle_request
    socket = self._get_socket(sid)
  File "/opt/beanfield/beanmachine/venvs/beanmachine/lib/python3.6/site-packages/engineio/server.py", line 562, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'

I traced it down to this: https://github.com/miguelgrinberg/python-engineio/blob/7a4e2780f9ea3466a8a14e3f1720561773faee7c/src/engineio/asyncio_server.py#L255

**To Reproduce**
1. Start the server which serves up data in a polling room
2. Join the polling room with multiple clients, the more the easier to replicate
3. restart the aiohttp server

**Expected behavior**
I did not expect to receive the following errors at all.  I estimated all the socket in self._sockets[sid] to be deleted already, instead of just being marked as closed.

**Logs**
2021-07-05 18:09:21,960 ERROR [aiohttp.server][MainThread] Error handling request
Traceback (most recent call last):
  File "/opt/beanfield/beanmachine/venvs/beanmachine/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/opt/beanfield/beanmachine/venvs/beanmachine/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/opt/beanfield/beanmachine/venvs/beanmachine/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/opt/beanfield/beanmachine/venvs/beanmachine/lib/python3.6/site-packages/engineio/asyncio_server.py", line 249, in handle_request
    socket = self._get_socket(sid)
  File "/opt/beanfield/beanmachine/venvs/beanmachine/lib/python3.6/site-packages/engineio/server.py", line 562, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'

**Additional context**
python-socketio==4.5.1
python-engineio==3.12.1
aiohttp==3.6.2

**Comment by miguelgrinberg** [comment]
How long did you wait to restart the server? If you are using polling it might take a while for the client to time out and start reconnection attempts.

Also, you are using fairly old releases. Current versions do not show a stack trace for this condition, they just write a message to the log.

**Comment by shasan-beanfield** [comment]
It seems one of the rooms wasn't emptied properly.  This isn't an error after all, just the leave_room function wasn't called.
