### ISSUE TITLE
Incompatibility with long-polling and Engine.IO protocol 4

### ISSUE THREAD

**Issue by felix-gohla** [miguelgrinberg/python-engineio#247]
When connecting to the [latest Socket.IO javascript server](https://github.com/socketio/engine.io) via `python-socketio` and therefore `python-engineio` via **long-polling**, a connection error happens and the connection is terminated.
See log output from the javascript server below.
 
**To Reproduce**

1. Create a simple socket.io server in Javascript.
2. Create a simple socket.io client python app with `python-engineio`, setting `transports=['polling']`. 
3. Try to connect.
4. See that it fails. :)

**Expected behavior**

The connection should succeed.

**Logs**

Logs from the *javascript server*:

```text
  engine intercepting request for path "/v1/events/" +0ms
  engine handling "GET" http request "/v1/events/?transport=polling&EIO=4&t=1631870852.943651" +1ms
  engine handshaking client "nDSNVa-cuugFr1qkAAAA" +2ms
  engine:socket sending packet "open" ({"sid":"nDSNVa-cuugFr1qkAAAA","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":20000}) +0ms
  engine:polling setting request +0ms
  engine:socket flushing buffer to transport +1ms
  engine:polling writing "0{"sid":"nDSNVa-cuugFr1qkAAAA","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":20000}" +0ms
  engine:socket executing batch send callback +3ms
  socket.io:server incoming connection with id nDSNVa-cuugFr1qkAAAA +4s
  engine intercepting request for path "/v1/events/" +77ms
  engine handling "POST" http request "/v1/events/?transport=polling&EIO=4&sid=nDSNVa-cuugFr1qkAAAA" +1ms
  engine setting new request for existing client +0ms
  engine:socket transport error +73ms
  engine:polling closing +77ms
  engine:polling transport not writable - buffering orderly close +0ms
  socket.io:client client close with reason transport error +0ms
  engine intercepting request for path "/v1/events/" +38ms
  engine handling "GET" http request "/v1/events/?transport=polling&EIO=4&sid=nDSNVa-cuugFr1qkAAAA&t=1631870853.0848148" +0ms
  engine unknown sid "nDSNVa-cuugFr1qkAAAA" +1ms
```

Logs from the *python client* (not the same session id, but the same problem):

```text
Attempting polling connection to http://localhost:3000/v1/events/?transport=polling&EIO=4
2021-09-17 12:31:42,900 INFO [engineio.client] Attempting polling connection to http://localhost:3000/v1/events/?transport=polling&EIO=4
2021-09-17 12:31:42,901 DEBUG [urllib3.connectionpool] Starting new HTTP connection (1): localhost:3000
2021-09-17 12:31:42,903 DEBUG [urllib3.connectionpool] http://localhost:3000 "GET /v1/events/?transport=polling&EIO=4&t=1631874702.900261 HTTP/1.1" 200 97
Polling connection accepted with {'sid': 'W8VnK1Oy7HHBaqNoAAAJ', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 20000}
2021-09-17 12:31:42,903 INFO [engineio.client] Polling connection accepted with {'sid': 'W8VnK1Oy7HHBaqNoAAAJ', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 20000}
Engine.IO connection established
2021-09-17 12:31:42,903 INFO [socketio.client] Engine.IO connection established
Sending packet MESSAGE data 0
2021-09-17 12:31:42,904 INFO [engineio.client] Sending packet MESSAGE data 0
Sending polling GET request to http://localhost:3000/v1/events/?transport=polling&EIO=4&sid=W8VnK1Oy7HHBaqNoAAAJ
2021-09-17 12:31:42,906 INFO [engineio.client] Sending polling GET request to http://localhost:3000/v1/events/?transport=polling&EIO=4&sid=W8VnK1Oy7HHBaqNoAAAJ
2021-09-17 12:31:42,908 DEBUG [urllib3.connectionpool] Starting new HTTP connection (2): localhost:3000
2021-09-17 12:31:42,909 DEBUG [urllib3.connectionpool] http://localhost:3000 "GET /v1/events/?transport=polling&EIO=4&sid=W8VnK1Oy7HHBaqNoAAAJ&t=1631874702.9070785 HTTP/1.1" 400 None
Unexpected status code 400 in server response, aborting
2021-09-17 12:31:42,910 WARNING [engineio.client] Unexpected status code 400 in server response, aborting
Waiting for write loop task to end
2021-09-17 12:31:42,910 INFO [engineio.client] Waiting for write loop task to end
Sending packet CLOSE data None
2021-09-17 12:31:43,907 INFO [engineio.client] Sending packet CLOSE data None
Engine.IO connection dropped
2021-09-17 12:31:43,907 INFO [socketio.client] Engine.IO connection dropped
Traceback (most recent call last):
  File "app/main.py", line 29, in <module>
    main()
  File "app/main.py", line 22, in main
    client.connect(wg_service)
  File "app/api/client.py", line 28, in connect
    self.sio.connect(self.base_url, socketio_path=self.ROUTER_EVENTS_ROUTE, headers={
  File "lib/python3.9/site-packages/socketio/client.py", line 338, in connect
    raise exceptions.ConnectionError(
socketio.exceptions.ConnectionError: One or more namespaces failed to connect
HTTP POST request to http://localhost:3000/v1/events/?transport=polling&EIO=4&sid=W8VnK1Oy7HHBaqNoAAAJ failed with error HTTPConnectionPool(host='localhost', port=3000): Read timed out. (read timeout=5).
2021-09-17 12:31:47,910 INFO [engineio.client] HTTP POST request to http://localhost:3000/v1/events/?transport=polling&EIO=4&sid=W8VnK1Oy7HHBaqNoAAAJ failed with error HTTPConnectionPool(host='localhost', port=3000): Read timed out. (read timeout=5).
Connection refused by the server, aborting
2021-09-17 12:31:47,910 WARNING [engineio.client] Connection refused by the server, aborting
Exiting write loop task
2021-09-17 12:31:47,910 INFO [engineio.client] Exiting write loop task
Exiting read loop task
2021-09-17 12:31:47,910 INFO [engineio.client] Exiting read loop task
```

**Additional context**

Connecting with a javascript client works flawlessly. We noticed that the javascript client sets the `Content-Type` header to `text/plain`.

**Comment by miguelgrinberg** [comment]
Yes, looks like I did not update the content type in the v4 protocol. Thanks.
