### ISSUE TITLE
Python 3.10 - PY_SSIZE_T_CLEAN macro must be defined for '#' formats

### ISSUE THREAD

**Issue by MaxwellDPS** [miguelgrinberg/python-engineio#268]
**Describe the bug**
Python 3.10 seems to introduce the following error `PY_SSIZE_T_CLEAN macro must be defined for '#' formats`

**To Reproduce**
1. Integrate with django 
2. Use python 3.10
3. Turn on logging and try to connect

**Expected behavior**
A successful websocket connection

**Logs**
```
trunk-player_1         | kSic9yN6dPgg5MZHAAAC: Sending packet OPEN data {'sid': 'kSic9yN6dPgg5MZHAAAC', 'upgrades': [], 'pingTimeout': 20000, 'pingInterval': 25000}
trunk-player_1         | INFO:engineio.server:kSic9yN6dPgg5MZHAAAC: Sending packet OPEN data {'sid': 'kSic9yN6dPgg5MZHAAAC', 'upgrades': [], 'pingTimeout': 20000, 'pingInterval': 25000}
trunk-player_1         | kSic9yN6dPgg5MZHAAAC: Received request to upgrade to websocket
trunk-player_1         | INFO:engineio.server:kSic9yN6dPgg5MZHAAAC: Received request to upgrade to websocket
trunk-player_1         | kSic9yN6dPgg5MZHAAAC: Upgrade to websocket successful
trunk-player_1         | INFO:engineio.server:kSic9yN6dPgg5MZHAAAC: Upgrade to websocket successful
trunk-player_1         | kSic9yN6dPgg5MZHAAAC: Unexpected error "PY_SSIZE_T_CLEAN macro must be defined for '#' formats", closing connection
trunk-player_1         | INFO:engineio.server:kSic9yN6dPgg5MZHAAAC: Unexpected error "PY_SSIZE_T_CLEAN macro must be defined for '#' formats", closing connection
trunk-player_1         | [pid: 1|app: 0|req: 29/28] 172.70.230.38 () {54 vars in 826 bytes} [Thu Feb  3 18:05:27 2022] GET /socket.io/?EIO=4&transport=websocket => generated 0 bytes in 4 msecs (HTTP/1.1 101) 4 headers in 164 bytes (2 switches on core 97)
```

**Additional context**
Django app in Docker container w/ uwsgi

These may be relevant
[https://bugs.python.org/issue40943](https://bugs.python.org/issue40943)
[https://www.python.org/dev/peps/pep-0353/](https://www.python.org/dev/peps/pep-0353/)

**Comment by miguelgrinberg** [comment]
I don't understand the connection between this error and this package. The error refers to some aspects of the C API of Python. This package is 100% Python code, there is no C.

**Comment by MaxwellDPS** [comment]
Agreed, its quite odd, but I can confirm exact same docker image works on 3.7, 3.8 and 3.9. but not 3.10. I have unpinned all pip packages

**Comment by miguelgrinberg** [comment]
The only thing I can suggest is that you remove the error handler in this package, so that the error can bubble up and print a stack trace. This is the line where the error is handled: https://github.com/miguelgrinberg/python-engineio/blob/45c46023401b7b7deae73f8229ab15255486c1e2/src/engineio/socket.py#L235. If you add a `raise` right after the error is logged, then you'll see a stack trace in your log. Maybe that'll give you more clues that point to the package that is faulting.

**Comment by MaxwellDPS** [comment]
@miguelgrinberg Thank you for the suggestion, I did that... heres the trace. Im a little lost as to what the offending package here is

```
trunk-player_1         | UZnD6BsGiTaFIVUfAAAA: Unexpected error "PY_SSIZE_T_CLEAN macro must be defined for '#' formats", closing connection
trunk-player_1         | INFO:engineio.server:UZnD6BsGiTaFIVUfAAAA: Unexpected error "PY_SSIZE_T_CLEAN macro must be defined for '#' formats", closing connection
trunk-player_1         | Traceback (most recent call last):
trunk-player_1         |   File "/usr/local/lib/python3.10/site-packages/engineio/middleware.py", line 63, in __call__
trunk-player_1         |     return self.engineio_app.handle_request(environ, start_response)
trunk-player_1         |   File "/usr/local/lib/python3.10/site-packages/socketio/server.py", line 597, in handle_request
trunk-player_1         |     return self.eio.handle_request(environ, start_response)
trunk-player_1         |   File "/usr/local/lib/python3.10/site-packages/engineio/server.py", line 398, in handle_request
trunk-player_1         |     r = self._handle_connect(environ, start_response,
trunk-player_1         |   File "/usr/local/lib/python3.10/site-packages/engineio/server.py", line 573, in _handle_connect
trunk-player_1         |     ret = s.handle_get_request(environ, start_response)
trunk-player_1         |   File "/usr/local/lib/python3.10/site-packages/engineio/socket.py", line 103, in handle_get_request
trunk-player_1         |     return getattr(self, '_upgrade_' + transport)(environ,
trunk-player_1         |   File "/usr/local/lib/python3.10/site-packages/engineio/socket.py", line 158, in _upgrade_websocket
trunk-player_1         |     return ws(environ, start_response)
trunk-player_1         |   File "/usr/local/lib/python3.10/site-packages/engineio/async_drivers/gevent_uwsgi.py", line 61, in __call__
trunk-player_1         |     self.app(self)
trunk-player_1         |   File "/usr/local/lib/python3.10/site-packages/engineio/socket.py", line 238, in _websocket_handler
trunk-player_1         |     raise(e)
trunk-player_1         |   File "/usr/local/lib/python3.10/site-packages/engineio/socket.py", line 230, in _websocket_handler
trunk-player_1         |     p = websocket_wait()
trunk-player_1         |   File "/usr/local/lib/python3.10/site-packages/engineio/socket.py", line 163, in websocket_wait
trunk-player_1         |     data = ws.wait()
trunk-player_1         |   File "/usr/local/lib/python3.10/site-packages/engineio/async_drivers/gevent_uwsgi.py", line 133, in wait
trunk-player_1         |     self._send(msg)
trunk-player_1         |   File "/usr/local/lib/python3.10/site-packages/engineio/async_drivers/gevent_uwsgi.py", line 81, in _send
trunk-player_1         |     method(msg)
trunk-player_1         | SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```

**Comment by miguelgrinberg** [comment]
I think uWSGI is the culprit. See https://github.com/unbit/uwsgi/pull/2363. This was merged, but no release has been issued with this fix yet.
