### ISSUE TITLE
Bug disconnection with uwsgi

### ISSUE THREAD

**Issue by johaven** [miguelgrinberg/python-engineio#330]
**Versions:**
Flask-SocketIO        5.3.5
python-engineio       4.6.1
python-socketio       5.8.0
gevent                23.7.0
greenlet              2.0.2
uWSGI                 2.0.22

**Error during disconnection:**
```python
[uwsgi-websocket] "GET /socket.io/?EIO=4&transport=websocket" no PONG received in 3 seconds !!!
[BUG] current_wsgi_req NOT FOUND !!!
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/var/www/webapp/venv/lib64/python3.9/site-packages/engineio/socket.py", line 223, in writer
    ws.close()
  File "/var/www/webapp/venv/lib64/python3.9/site-packages/engineio/async_drivers/gevent_uwsgi.py", line 70, in close
    uwsgi.disconnect()
SystemError: you can call uwsgi api function only from the main callable
2023-09-06T08:59:59Z <Thread at 0x7febf566dae0: writer> failed with SystemError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 833, in gevent._gevent_cgreenlet.Greenlet.join
  File "src/gevent/greenlet.py", line 859, in gevent._gevent_cgreenlet.Greenlet.join
  File "src/gevent/greenlet.py", line 848, in gevent._gevent_cgreenlet.Greenlet.join
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/var/www/webapp/venv/lib64/python3.9/site-packages/engineio/socket.py", line 223, in writer
    ws.close()
  File "/var/www/webapp/venv/lib64/python3.9/site-packages/engineio/async_drivers/gevent_uwsgi.py", line 70, in close
    uwsgi.disconnect()
SystemError: you can call uwsgi api function only from the main callable
```
**Seems to be related to:**

https://github.com/unbit/uwsgi/pull/985
https://github.com/pinterest/querybook/issues/1319

**Comment by stianpr** [comment]
Any updates on this?

**Comment by amks1** [comment]
I have the same issue, python-engineio v4.5.1 is the latest version I'm able to run that doesn't give the above error.

**Comment by miguelgrinberg** [comment]
Could you test the main branch to confirm the problem is gone? Thanks.

**Comment by amks1** [comment]
> Could you test the main branch to confirm the problem is gone? Thanks.

Yes, the problem seems to be fixed in the main branch now. 👍

**Comment by miguelgrinberg** [comment]
4.7.1 is out with this fix.

**Comment by okayhooni** [comment]
@johaven 
Thank you for noticing me this issue with mention. :)
