### ISSUE TITLE
New 1.5.0 release fails

### ISSUE THREAD

**Issue by Stuffedgame** [miguelgrinberg/python-engineio#46]
127.0.0.1 - - [09/May/2017 18:38:35] "GET /socket.io/?EIO=4&transport=websocket HTTP/1.1" 500 1691 0.008256
(1350) accepted ('127.0.0.1', 43807)
connect  54ce2d3a92054ba0aedb6e3e2a5c24d6
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/eventlet/wsgi.py", line 507, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/socketio/server.py", line 353, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/engineio/server.py", line 252, in handle_request
    transport, b64)
  File "/usr/local/lib/python3.5/dist-packages/engineio/server.py", line 374, in _handle_connect
    ret = s.handle_get_request(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/engineio/socket.py", line 89, in handle_get_request
    start_response)
  File "/usr/local/lib/python3.5/dist-packages/engineio/socket.py", line 136, in _upgrade_websocket
    return ws(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/engineio/async_eventlet.py", line 19, in __call__
    return super(WebSocketWSGI, self).__call__(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/eventlet/websocket.py", line 127, in __call__
    self.handler(ws)
  File "/usr/local/lib/python3.5/dist-packages/engineio/socket.py", line 142, in _websocket_handler
    if hasattr(ws, attr) and hasattr(ws.attr, 'settimeout'):
AttributeError: 'RFC6455WebSocket' object has no attribute 'attr'

I think because the code in engineio/socket.py is:

            if hasattr(ws, attr) and hasattr(ws.attr, 'settimeout'):

rather than something like:  

if hasattr(ws, attr) and hasattr(getattr(ws, attr), 'settimeout'):

**Comment by Stuffedgame** [comment]
I tested my proposed fix, and it works.

**Comment by miguelgrinberg** [comment]
Yep, I rushed a release last night and missed this. Release 1.5.1 has this fix. Thanks!
