### ISSUE TITLE
Bad error handling regarding event listener signature

### ISSUE THREAD

**Issue by MarSoft** [miguelgrinberg/python-engineio#54]
Let's consider the following setup: we use `socketio` with some `asyncio`-based server (like `sanic`). We subscribed to some custom message and expect just one data argument for it:
```python
from sanic import Sanic
import socketio

app = Sanic(__name__)
sio = socketio.AsyncServer(async_mode='sanic')
sio.attach(app)

@sio.on('custom message')
async def on_custom_message(sid, data):
    print('Got data {} from sid {}'.format(data, sid))

app.run()
```
Now we connect to this server and send message with incorrect data values count:
```js
var io = require('socket.io-client');
var socket = io();
socket.emit('custom message', 1, 2);
```
Here is what we get in the server's logs:
```
2017-06-20 00:03:30 - (sanic)[INFO]: Goin' Fast @ http://127.0.0.1:8000
2017-06-20 00:03:30 - (sanic)[INFO]: Starting worker [29888]
2017-06-20 00:03:32 - (network)[INFO][127.0.0.1:34022]: GET http://localhost:8000/socket.io/?EIO=3&transport=polling&t=Lp2Akw4&b64=1  200 117
yo
2017-06-20 00:03:32 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/tmp/env/lib/python3.6/site-packages/sanic/app.py", line 471, in handle_request
    response = await response
  File "/tmp/env/lib/python3.6/site-packages/engineio/asyncio_server.py", line 135, in handle_request
    socket = self._get_socket(sid)
  File "/tmp/env/lib/python3.6/site-packages/engineio/server.py", line 411, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'

2017-06-20 00:03:32 - (network)[INFO][127.0.0.1:34028]: GET http://localhost:8000/socket.io/?EIO=3&transport=polling&t=Lp2Akwd&b64=1&sid=68f480e234f546f980340d107e3cda62  500 144
2017-06-20 00:03:32 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/tmp/env/lib/python3.6/site-packages/sanic/app.py", line 471, in handle_request
    response = await response
  File "/tmp/env/lib/python3.6/site-packages/engineio/asyncio_server.py", line 137, in handle_request
    packets = await socket.handle_get_request(environ)
  File "/tmp/env/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 73, in handle_get_request
    return await getattr(self, '_upgrade_' + transport)(environ)
  File "/tmp/env/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 120, in _upgrade_websocket
    return await ws(environ)
  File "/tmp/env/lib/python3.6/site-packages/engineio/async_sanic.py", line 122, in __call__
    await self.handler(self)
  File "/tmp/env/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 138, in _websocket_handler
    await self.send(packet.Packet(packet.NOOP))
  File "/tmp/env/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 53, in send
    raise IOError('Socket is closed')
OSError: Socket is closed

2017-06-20 00:03:33 - (network)[INFO][127.0.0.1:34030]: GET http://localhost:8000/socket.io/?EIO=3&transport=polling&t=Lp2Al5F&b64=1  200 117
2017-06-20 00:03:33 - (network)[INFO][127.0.0.1:34034]: GET http://localhost:8000/socket.io/?EIO=3&transport=polling&t=Lp2Al5Q&b64=1&sid=b13efb25fbd945f580bf7e5333623304  200 3
```

As a result, original exception (`on_custom_message() takes 2 positional arguments but 3 were given`) is not displayed at all, the only thing suggesting what happened is a mysterious `yo` message which is followed by some internal errors.

I think we could at least print basic exception information before disconnecting socket (see `asyncio_server.py` line `164`), because disconnection itself (together with its event handlers) may produce some other errors which will not allow us to see the original error.

**Comment by miguelgrinberg** [comment]
Oh yeah, that was unintentional. This needs to be fixed, sorry about that.

**Comment by miguelgrinberg** [comment]
@MarSoft I believe 8cc004a4a8014924dd822ca14ecabdad4e858c0d addresses your issue. Can I ask you to install the master branch direct from git and confirm? I want to do some more tests before I cut a release, but I think this should be out in a few days at the most.

**Comment by miguelgrinberg** [comment]
Thanks. I was actually testing with aiohttp instead of sanic. Turns out sanic disables all loggers except their own. There is an existing issue about this: https://github.com/channelcat/sanic/issues/805

I have modified your test application above to re-enable my loggers in the connect handler:

```python
from sanic import Sanic
import socketio

app = Sanic(__name__)
sio = socketio.AsyncServer(async_mode='sanic')
sio.attach(app)

@sio.on('connect')
async def connect(sid, environ):
    import logging
    logging.getLogger('engineio').disabled = False
    logging.getLogger('socketio').disabled = False

@sio.on('custom message')
async def on_custom_message(sid, data):
    print('Got data {} from sid {}'.format(data, sid))

app.run()
```

Does this fix the problem? Hopefully the Sanic developers will address this on their side soon.

**Comment by miguelgrinberg** [comment]
I'm closing this issue as fixed, and will follow up with Sanic team regarding the logging problem.
