### ISSUE TITLE
TypeError when disconnecting 

### ISSUE THREAD

**Issue by Hoppaz** [miguelgrinberg/python-engineio#59]
Hi,

I've got an equal error like #3 
using python-engineio==1.7.0
```
20171209 08:46:00 INFO: [default main.py:177: disconnect
Traceback (most recent call last):
  File "/home/lars/src/virsh-web/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 935, in handle_one_response
    self.run_application()
  File "/home/lars/src/virsh-web/local/lib/python2.7/site-packages/geventwebsocket/handler.py", line 87, in run_application
    return super(WebSocketHandler, self).run_application()
  File "/home/lars/src/virsh-web/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 908, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/home/lars/src/virsh-web/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/lars/src/virsh-web/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 42, in __call__
    start_response)
  File "/home/lars/src/virsh-web/local/lib/python2.7/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/lars/src/virsh-web/local/lib/python2.7/site-packages/socketio/server.py", line 360, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/lars/src/virsh-web/local/lib/python2.7/site-packages/engineio/server.py", line 267, in handle_request
    environ, start_response)
  File "/home/lars/src/virsh-web/local/lib/python2.7/site-packages/engineio/socket.py", line 94, in handle_get_request
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
Sat Dec  9 08:46:00 2017 {'REMOTE_PORT': '56166', 'HTTP_HOST': 'localhost:8002', 'REMOTE_ADDR': '127.0.0.1', (hidden keys: 24)} failed with TypeError
```
Fixed it in an similar way in python2.7/site-packages/engineio/socket.py:
     92         except exceptions.QueueEmpty as e:
     93             self.close(wait=False)
     94             raise e

**Comment by miguelgrinberg** [comment]
Yes, this was already reported, and is fixed by 4a3320051aac532918b1e0448aad8cc8da615697. A new release with this fix coming up shortly.
