### ISSUE TITLE
OSError using with aiohttp

### ISSUE THREAD

**Issue by brunoalano** [miguelgrinberg/python-engineio#69]
I'm getting IOError when using `python-socketio` with `aiohttp` library. Actually I'm using the `uvloop` implementation for event loop, but changing to the default one, doesn't change anything.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_app.py", line 322, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.6/site-packages/engineio/asyncio_server.py", line 146, in handle_request
    packets = await socket.handle_get_request(environ)
  File "/usr/local/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 76, in handle_get_request
    return await getattr(self, '_upgrade_' + transport)(environ)
  File "/usr/local/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 118, in _upgrade_websocket
    return await ws(environ)
  File "/usr/local/lib/python3.6/site-packages/engineio/async_aiohttp.py", line 96, in __call__
    await self.handler(self)
  File "/usr/local/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 138, in _websocket_handler
    pkt = await ws.wait()
  File "/usr/local/lib/python3.6/site-packages/engineio/async_aiohttp.py", line 116, in wait
    raise IOError()
OSError
```

__Dependencies__
```
python-engineio==2.1.0
python-socketio==1.9.0
uvloop==0.9.1
aiohttp==3.1.3
```

**Comment by miguelgrinberg** [comment]
I can't reproduce this with the example applications in this repository. Do you have an example I can use?

**Comment by brunoalano** [comment]
I am trying to reproduce it too, since I only see this error when I deploy to millions of users. Activating the `engineio_logger` doesnt show any meaningful information.

I will try to find the cause and will keep you updatd.

**Comment by miguelgrinberg** [comment]
I assume the affected client is disconnected but the server does not stop serving other clients.

**Comment by brunoalano** [comment]
The issue was ocurring on my Ingress Controller (Kubernetes).
