### ISSUE TITLE
Can someone point to where the problem might be

### ISSUE THREAD

**Issue by abylikhsanov** [miguelgrinberg/python-engineio#84]
Hi,

I have quite a big code which I am reviewing and one of the app is using engineio + socketio.
Basically, one app sends a JSON object to the webserver. Then the webserver uses engineio to handle requests.

When it happens, I get this error:
```
2018-12-03T10:31:41.111811+00:00 app[web.1]: 10:31:41 engineio     INFO     282616268e264412b8cbfc042982572f: Sending packet PONG data probe
2018-12-03T10:31:43.960388+00:00 app[web.1]: 10:31:43 engineio     INFO     282616268e264412b8cbfc042982572f: Received packet MESSAGE data 5["post_state", "[{\"wheelId\":\"LEFT_FRONT\",\"heading\":0,\"raised\":true,\"batt\":4.04,\"position\":{\"x\":0,\"y\":0}},{\"wheelId\":\"RIGHT_FRONT\",\"heading\":0,\"raised\":true,\"batt\":0,\"position\":{\"x\":0,\"y\":0}},{\"wheelId\":\"LEFT_REAR\",\"heading\":0,\"raised\":true,\"batt\":0,\"position\":{\"x\":0,\"y\":0}},{\"wheelId\":\"RIGHT_REAR\",\"heading\":0,\"raised\":true,\"batt\":0,\"position\":{\"x\":0,\"y\":0}}]"]
2018-12-03T10:31:43.960887+00:00 app[web.1]: 10:31:43 engineio     ERROR    message handler error
2018-12-03T10:31:43.960890+00:00 app[web.1]: Traceback (most recent call last):
2018-12-03T10:31:43.960892+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/engineio/server.py", line 405, in _trigger_event
2018-12-03T10:31:43.960893+00:00 app[web.1]: return self.handlers[event](*args)
2018-12-03T10:31:43.960895+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 509, in _handle_eio_message
2018-12-03T10:31:43.960896+00:00 app[web.1]: if pkt.add_attachment(data):
2018-12-03T10:31:43.960898+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/packet.py", line 118, in add_attachment
2018-12-03T10:31:43.960899+00:00 app[web.1]: raise ValueError('Unexpected binary attachment')
2018-12-03T10:31:43.960935+00:00 app[web.1]: ValueError: Unexpected binary attachment
```

Can you please tell me what I might be doing wrong here? Is it due to the b64 variable?

**Comment by miguelgrinberg** [comment]
What client are you using? This error seems to suggest the client sent a binary packet when none was expected.

**Comment by abylikhsanov** [comment]
When you say client, what exactly do you mean?

**Comment by miguelgrinberg** [comment]
This is a socket.io server. I'm asking about the client that connects to
the server.

**Comment by abylikhsanov** [comment]
["post_state", "[{\"wheelId\":\"LEFT_FRONT\",\"heading\":0,\"raised\":true,\"batt\":4.072,\"position\":{\"x\":0,\"y\":0}},{\"wheelId\":\"RIGHT_FRONT\",\"heading\":0,\"raised\":true,\"batt\":0,\"position\":{\"x\":0,\"y\":0}},{\"wheelId\":\"LEFT_REAR\",\"heading\":0,\"raised\":true,\"batt\":0,\"position\":{\"x\":0,\"y\":0}},{\"wheelId\":\"RIGHT_REAR\",\"heading\":0,\"raised\":true,\"batt\":0,\"position\":{\"x\":0,\"y\":0}}]"]

This is what I am sending to the socket, if that matters

**Comment by JoseRaffucci** [comment]
@abylikhsanov Did you attempt to send the same message with the standard library to test your endpoint?

**Comment by miguelgrinberg** [comment]
@abylikhsanov I think you are missing what I and @JoseRaffucci are telling you. This server is specialized. You can't open a socket connection from your C app and write some data to it. I do not know of any Socket.IO client implementation for C, but there is one for C++: https://github.com/socketio/socket.io-client-cpp. You need this or similar client to talk to a Socket.IO server.
