### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by teucer** [miguelgrinberg/python-engineio#92]
With python-engineio = "3.1.0" I am getting RecursionError: maximum recursion depth exceeded:

```
 File "[...]\site-packages\urllib3\util\ssl_.py", line 281, in create_urllib3_context
    context.options |= options
  File "[...]\miniconda\envs\py36\lib\ssl.py", line 465, in options
     super(SSLContext, SSLContext).options.__set__(self, value)
```
Only two fixes so far:
+ Either pin  python-engineio to 3.0.0
+ eventlet.monkey_patch(socket=False)

**Details:**
+ python 3.6.8
+ windows 7
+ conda 4.5.12
+ eventlet 0.24.1

**Comment by miguelgrinberg** [comment]
Can you share the complete stack trace please? The portion that you shared doesn't have enough context for me to understand what's going on.

**Comment by teucer** [comment]
`ERROR: Exception on /auth/login [POST] [in c:\user\dev\venvs\flask_36\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\user\dev\venvs\flask_36\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\user\dev\venvs\flask_36\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\user\dev\venvs\flask_36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\user\dev\venvs\flask_36\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\user\dev\venvs\flask_36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\user\dev\venvs\flask_36\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\user\dev\venvs\flask_36\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\user\Dev\projects\vue_bare\app\backend\auth\views.py", line 14, in login
    if user is not None and user.verify_password(password):
  File "C:\user\Dev\projects\vue_bare\app\backend\models.py", line 69, in verify_password
    return check_page_login(self.username, password)
  File "C:\user\Dev\projects\vue_bare\app\backend\authenticate.py", line 13, in check_page_login
    r = s.get(url_page, auth=(username, password))
  File "c:\user\dev\venvs\flask_36\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "c:\user\dev\venvs\flask_36\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\user\dev\venvs\flask_36\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "c:\user\dev\venvs\flask_36\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\user\dev\venvs\flask_36\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\user\dev\venvs\flask_36\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "c:\user\dev\venvs\flask_36\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "c:\user\dev\venvs\flask_36\lib\site-packages\urllib3\connection.py", line 332, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "c:\user\dev\venvs\flask_36\lib\site-packages\urllib3\util\ssl_.py", line 281, in create_urllib3_context
    context.options |= options
  File "C:\user\Dev\apps\miniconda\envs\py36\lib\ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "C:\user\Dev\apps\miniconda\envs\py36\lib\ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "C:\user\Dev\apps\miniconda\envs\py36\lib\ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 304 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object`

**Comment by teucer** [comment]
`ERROR: Exception on /auth/login [POST] [in c:\user\dev\venvs\flask_36\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\user\dev\venvs\flask_36\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\user\dev\venvs\flask_36\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\user\dev\venvs\flask_36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\user\dev\venvs\flask_36\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\user\dev\venvs\flask_36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\user\dev\venvs\flask_36\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\user\dev\venvs\flask_36\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\user\Dev\projects\vue_bare\app\backend\auth\views.py", line 14, in login
    if user is not None and user.verify_password(password):
  File "C:\user\Dev\projects\vue_bare\app\backend\models.py", line 69, in verify_password
    return check_page_login(self.username, password)
  File "C:\user\Dev\projects\vue_bare\app\backend\authenticate.py", line 13, in check_page_login
    r = s.get(url_page, auth=(username, password))
  File "c:\user\dev\venvs\flask_36\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "c:\user\dev\venvs\flask_36\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\user\dev\venvs\flask_36\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "c:\user\dev\venvs\flask_36\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\user\dev\venvs\flask_36\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\user\dev\venvs\flask_36\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "c:\user\dev\venvs\flask_36\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "c:\user\dev\venvs\flask_36\lib\site-packages\urllib3\connection.py", line 332, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "c:\user\dev\venvs\flask_36\lib\site-packages\urllib3\util\ssl_.py", line 281, in create_urllib3_context
    context.options |= options
  File "C:\user\Dev\apps\miniconda\envs\py36\lib\ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "C:\user\Dev\apps\miniconda\envs\py36\lib\ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "C:\user\Dev\apps\miniconda\envs\py36\lib\ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 304 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object`

**Comment by teucer** [comment]
```
ERROR:

 Exception on /auth/login [POST] [in c:\user\dev\venvs\flask_36\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  
File "c:\user\dev\venvs\flask_36\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  
File "c:\user\dev\venvs\flask_36\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  
File "c:\user\dev\venvs\flask_36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  
File "c:\user\dev\venvs\flask_36\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  
File "c:\user\dev\venvs\flask_36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  
File "c:\user\dev\venvs\flask_36\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  
File "c:\user\dev\venvs\flask_36\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  
File "C:\user\Dev\projects\vue_bare\app\backend\auth\views.py", line 14, in login
    if user is not None and user.verify_password(password):
  
File "C:\user\Dev\projects\vue_bare\app\backend\models.py", line 69, in verify_password
    return check_page_login(self.username, password)
  
File "C:\user\Dev\projects\vue_bare\app\backend\authenticate.py", line 13, in check_page_login
    r = s.get(url_page, auth=(username, password))
  
File "c:\user\dev\venvs\flask_36\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  
File "c:\user\dev\venvs\flask_36\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  
File "c:\user\dev\venvs\flask_36\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
 
File "c:\user\dev\venvs\flask_36\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  
File "c:\user\dev\venvs\flask_36\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  
File "c:\user\dev\venvs\flask_36\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  
File "c:\user\dev\venvs\flask_36\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  
File "c:\user\dev\venvs\flask_36\lib\site-packages\urllib3\connection.py", line 332, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  
File "c:\user\dev\venvs\flask_36\lib\site-packages\urllib3\util\ssl_.py", line 281, in create_urllib3_context
    context.options |= options
  
File "C:\user\Dev\apps\miniconda\envs\py36\lib\ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  
File "C:\user\Dev\apps\miniconda\envs\py36\lib\ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  
File "C:\user\Dev\apps\miniconda\envs\py36\lib\ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  
[Previous line repeated 304 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by miguelgrinberg** [comment]
This doesn't appear to be related to python-engineio, note that there isn't a single reference to it in your stack trace. On the other side, this issue regarding monkey patching too late looks related to your problem: https://github.com/gevent/gevent/issues/1016.

**Comment by teucer** [comment]
Pinning the version of python-engineio solves the issue (?)

**Comment by miguelgrinberg** [comment]
@teucer did you look at the link I sent?

**Comment by teucer** [comment]
@miguelgrinberg yes I did have look. I believe that the issue is not with the order of the imports. The only thing that has changed is the version of python-engineio. The code is the same: it works with the old version and does not work with the new one.

**Comment by miguelgrinberg** [comment]
@teucer this error occurs with improper monkey patching. You seem to be fixated on the pinning, but that is not indicative that the problem is in this package, it just means that something that I changed now exposes this bug, which is probably in your application.

For starters, you are not monkey patching socket, I now see. How do you expect requests to work without a monkey patched socket library?

**Comment by teucer** [comment]
Below is the beginning __init__.py of my flask app 
```
import logging
import os
import time

import eventlet

eventlet.monkey_patch()
```

This is called from a run.py 

```
import subprocess
import sys

import click
from flask_migrate import Migrate, upgrade

from app import create_app, db

app = create_app()
migrate = Migrate(app, db)
```

So far it was working...

**Comment by miguelgrinberg** [comment]
From http://eventlet.net/doc/patching.html#monkeypatching-the-standard-library:

> It is important to call monkey_patch() as early in the lifetime of the application as possible. Try to do it as one of the first lines in the main module.

**Comment by teucer** [comment]
modified run.py to have 

```
import eventlet
eventlet.monkey_patch()
```

as the first statement to no avail: I am getting the same error

**Comment by miguelgrinberg** [comment]
All the documented instances of this bug were proven to be due to a bad monkey patching, so I have to suspect you still have a problem there. Unless you can provide something I can use to debug this I do not know what else I can do to get to the bottom of this issue.

**Comment by teucer** [comment]
I think the recent updates might have exposed some bugs in `eventlet`, when I uninstall `flask-socketio` it works.  Is there a changelog?

**Comment by miguelgrinberg** [comment]
You can look at the commit list: https://github.com/miguelgrinberg/python-engineio/commits/master. All releases are clearly marked with a dedicated commit.

**Comment by teucer** [comment]
If I don't import `eventlet ` and don't patch (I am not using it anywhere, thought it was required by socketio somehow), it works.

**Comment by teucer** [comment]
Removing the lines

```
import eventlet
eventlet.monkey_patch()
```
fixes the problem.

**Comment by miguelgrinberg** [comment]
It may seem as if the problem is fixed, but that is not the right solution. Without monkey patching your requests calls are going to be blocking.

**Comment by teucer** [comment]
I am deploying the app with `gunicorn `and `eventlet `workers. Could you please let me know where the calls would be blocking.

PS: I am not using eventlet anywhere else in the code.

**Comment by miguelgrinberg** [comment]
Read up on the topic here: http://eventlet.net/doc/patching.html#greening-the-world

The important concept is this:

> One of the challenges of writing a library like Eventlet is that the built-in networking libraries don’t natively support the sort of cooperative yielding that we need.

You are using requests, which uses the built-in networking libraries in Python.

**Comment by royrusso** [comment]
Sorry to reopen, but related: https://github.com/eventlet/eventlet/issues/371
